### ISSUE TITLE
load_image_dataset  not found

### ISSUE THREAD

**Issue by mquinteiro** [jhfjhfj1/autokeras#100]
Following the instructions of https://autokeras.com/start/
I've found this error
Loading load_image_dataset with 
`from autokeras.image_classifier import load_image_dataset`
rise an error " No module named 'autokeras.image_classifier'"

checking the script in the 
rise the error from different module "from autokeras.classifier import load_image_dataset"

I've found the function in the module image_supervised.py

**Comment by jhfjhfj1** [comment]
@ankapale Would you please help change it in the start.md file?
Thanks.

**Comment by ManuelLevi** [comment]
I don't mind changing this if needed.

**Comment by jhfjhfj1** [comment]
@ManuelLevi Thank you so much!
Please change it.
Appreciate your help.

@ankapale you can focus on the other issues.
Thanks.
