### ISSUE TITLE
something error with getting the best result of cifar10

### ISSUE THREAD

**Issue by xialulu826** [jhfjhfj1/autokeras#116]
hi,
 when I run .\examples\cifar10.py,firstly everything is ok,but after Epoch66,the code stopped,the following is the detail,think for your answering.

"C:\Program Files\Python36\python.exe" D:/devkit_tracking/autokeras-0.2.1/examples/cifar10.py
C:\Program Files\Python36\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Initializing search.
Initialization finished.
Training model  0
C:\Program Files\Python36\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
....................................
Epoch 1: loss 48.80426788330078, accuracy 47.22822174226062
....................................
Epoch 2: loss 44.42049789428711, accuracy 52.89176865850732
....................................
Epoch 3: loss 42.31005096435547, accuracy 54.18766498680105
....................................
Epoch 4: loss 40.351016998291016, accuracy 56.563474922006236
....................................
Epoch 5: loss 40.085304260253906, accuracy 55.8675305975522
....................................
Epoch 6: loss 37.917144775390625, accuracy 59.827213822894166
....................................
Epoch 7: loss 37.82439041137695, accuracy 59.875209983201344
....................................
Epoch 8: loss 38.54084777832031, accuracy 58.84329253659707
....................................
Epoch 9: loss 37.29292678833008, accuracy 60.13918886489081
....................................
Epoch 10: loss 36.19758605957031, accuracy 61.86705063594913
....................................
Epoch 11: loss 35.71870422363281, accuracy 61.98704103671706
....................................
Epoch 12: loss 35.17670440673828, accuracy 63.37892968562515
....................................
Epoch 13: loss 35.09778594970703, accuracy 63.37892968562515
....................................
Epoch 14: loss 34.261470794677734, accuracy 63.64290856731461
....................................
Epoch 15: loss 34.421566009521484, accuracy 64.33885289176865
....................................
Epoch 16: loss 34.30224609375, accuracy 63.59491240700744
....................................
Epoch 17: loss 34.02406311035156, accuracy 64.0748740100792
....................................
Epoch 18: loss 33.18902587890625, accuracy 65.0347972162227
....................................
Epoch 19: loss 33.176395416259766, accuracy 65.39476841852652
....................................
Epoch 20: loss 33.716087341308594, accuracy 64.05087592992561
....................................
Epoch 21: loss 33.403533935546875, accuracy 64.57883369330453
....................................
Epoch 22: loss 32.9720344543457, accuracy 65.49076073914087
....................................
Epoch 23: loss 32.635032653808594, accuracy 65.89872810175186
....................................
Epoch 24: loss 32.3167610168457, accuracy 65.53875689944805
....................................
Epoch 25: loss 32.33857345581055, accuracy 66.2107031437485
....................................
Epoch 26: loss 33.478424072265625, accuracy 64.48284137269019
....................................
Epoch 27: loss 31.90555191040039, accuracy 66.8106551475882
....................................
Epoch 28: loss 31.922758102416992, accuracy 66.04271658267339
....................................
Epoch 29: loss 31.769996643066406, accuracy 67.0026397888169
....................................
Epoch 30: loss 32.07068634033203, accuracy 66.09071274298056
....................................
Epoch 31: loss 31.733060836791992, accuracy 67.0026397888169
....................................
Epoch 32: loss 31.532672882080078, accuracy 67.14662826973841
....................................
Epoch 33: loss 31.78310203552246, accuracy 66.76265898728101
....................................
Epoch 34: loss 31.222070693969727, accuracy 67.170626349892
....................................
Epoch 35: loss 31.330495834350586, accuracy 66.57067434605231
....................................
Epoch 36: loss 31.010828018188477, accuracy 67.41060715142788
....................................
Epoch 37: loss 31.326351165771484, accuracy 67.14662826973841
....................................
Epoch 38: loss 31.47686195373535, accuracy 66.4026877849772
....................................
Epoch 39: loss 31.304813385009766, accuracy 66.9786417086633
....................................
Epoch 40: loss 31.42787742614746, accuracy 66.90664746820255
....................................
Epoch 41: loss 31.324193954467773, accuracy 66.49868010559155
....................................
Epoch 42: loss 30.773801803588867, accuracy 67.43460523158147
....................................
Epoch 43: loss 31.23522186279297, accuracy 67.12263018958484
....................................
Epoch 44: loss 30.887908935546875, accuracy 67.89056875449964
....................................
Epoch 45: loss 30.536348342895508, accuracy 67.3866090712743
....................................
Epoch 46: loss 30.796695709228516, accuracy 66.45068394528438
....................................
Epoch 47: loss 31.02267837524414, accuracy 67.24262059035277
....................................
Epoch 48: loss 30.272396087646484, accuracy 67.53059755219583
....................................
Epoch 49: loss 31.18903160095215, accuracy 66.52267818574514
....................................
Epoch 50: loss 30.27387237548828, accuracy 68.32253419726422
....................................
Epoch 51: loss 30.756324768066406, accuracy 67.81857451403887
....................................
Epoch 52: loss 30.106008529663086, accuracy 68.10655147588193
....................................
Epoch 53: loss 30.574302673339844, accuracy 67.67458603311735
....................................
Epoch 54: loss 30.22770881652832, accuracy 68.22654187664986
....................................
Epoch 55: loss 29.99200439453125, accuracy 68.65850731941444
....................................
Epoch 56: loss 30.453886032104492, accuracy 67.93856491480682
....................................
Epoch 57: loss 30.077186584472656, accuracy 68.34653227741781
....................................
Epoch 58: loss 30.0889892578125, accuracy 68.46652267818574
....................................
Epoch 59: loss 29.739351272583008, accuracy 68.82649388048956
....................................
Epoch 60: loss 30.448667526245117, accuracy 67.77057835373171
....................................
Epoch 61: loss 30.61048126220703, accuracy 67.67458603311735
....................................
Epoch 62: loss 29.84048080444336, accuracy 68.13054955603552
....................................
Epoch 63: loss 30.002206802368164, accuracy 68.87449004079673
....................................
Epoch 64: loss 30.04825782775879, accuracy 68.10655147588193
....................................
Epoch 65: loss 30.07265281677246, accuracy 68.65850731941444
....................................
Epoch 66: loss 29.8739070892334, accuracy 69.04247660187185
No loss decrease after 5 epochs
THCudaCheck FAIL file=c:\users\administrator\downloads\new-builder\win-wheel\pytorch\torch\csrc\generic\StorageSharing.cpp line=253 error=63 : OS call failed or operation not supported on this OS
Traceback (most recent call last):
  File "D:/devkit_tracking/autokeras-0.2.1/examples/cifar10.py", line 9, in <module>
    clf.fit(x_train, y_train, time_limit=12 * 60 * 60)
  File "C:\Program Files\Python36\lib\site-packages\autokeras\classifier.py", line 225, in fit
    run_searcher_once(train_data, test_data, self.path)
  File "C:\Program Files\Python36\lib\site-packages\autokeras\classifier.py", line 40, in run_searcher_once
    searcher.search(train_data, test_data)
  File "C:\Program Files\Python36\lib\site-packages\autokeras\search.py", line 190, in search
    accuracy, loss, graph = train_results.get()[0]
  File "C:\Program Files\Python36\lib\multiprocessing\pool.py", line 644, in get
    raise self._value
multiprocessing.pool.MaybeEncodingError: Error sending result: '[(68.56251499880008, tensor(29.9675, device='cuda:0'), <autokeras.graph.Graph object at 0x0000000019E90128>)]'. Reason: 'RuntimeError('cuda runtime error (63) : OS call failed or operation not supported on this OS at c:\\users\\administrator\\downloads\\new-builder\\win-wheel\\pytorch\\torch\\csrc\\generic\\StorageSharing.cpp:253',)'

Process finished with exit code 1

**Comment by jhfjhfj1** [comment]
@xialulu826 Please use the bug report template to specify the needed information.
Thanks.

**Comment by xialulu826** [comment]
Bug Description
when I run .\examples\cifar10.py,firstly everything is ok,after some time, suddenly an error occurred :

"C:\Program Files\Python36\python.exe" D:/devkit_tracking/autokeras-0.2.1/examples/cifar10.py
C:\Program Files\Python36\lib\site-packages\h5py_init_.py:36: FutureWarning: Conversion of the second argument of issubdtype from float to np.floating is deprecated. In future, it will be treated as np.float64 == np.dtype(float).type.
from ._conv import register_converters as register_converters
Using TensorFlow backend.
Initializing search.
Initialization finished.
Training model 0
C:\Program Files\Python36\lib\site-packages\h5py_init.py:36: FutureWarning: Conversion of the second argument of issubdtype from float to np.floating is deprecated. In future, it will be treated as np.float64 == np.dtype(float).type.
from ._conv import register_converters as _register_converters
Using TensorFlow backend.
....................................
Epoch 1: loss 48.80426788330078, accuracy 47.22822174226062
....................................
Epoch 2: loss 44.42049789428711, accuracy 52.89176865850732
....................................
Epoch 3: loss 42.31005096435547, accuracy 54.18766498680105
....................................
Epoch 4: loss 40.351016998291016, accuracy 56.563474922006236
....................................
Epoch 5: loss 40.085304260253906, accuracy 55.8675305975522
....................................
Epoch 6: loss 37.917144775390625, accuracy 59.827213822894166
....................................
Epoch 7: loss 37.82439041137695, accuracy 59.875209983201344
....................................
Epoch 8: loss 38.54084777832031, accuracy 58.84329253659707
....................................
Epoch 9: loss 37.29292678833008, accuracy 60.13918886489081
....................................
Epoch 10: loss 36.19758605957031, accuracy 61.86705063594913
....................................
Epoch 11: loss 35.71870422363281, accuracy 61.98704103671706
....................................
Epoch 12: loss 35.17670440673828, accuracy 63.37892968562515
....................................
Epoch 13: loss 35.09778594970703, accuracy 63.37892968562515
....................................
Epoch 14: loss 34.261470794677734, accuracy 63.64290856731461
....................................
Epoch 15: loss 34.421566009521484, accuracy 64.33885289176865
....................................
Epoch 16: loss 34.30224609375, accuracy 63.59491240700744
....................................
Epoch 17: loss 34.02406311035156, accuracy 64.0748740100792
....................................
Epoch 18: loss 33.18902587890625, accuracy 65.0347972162227
....................................
Epoch 19: loss 33.176395416259766, accuracy 65.39476841852652
....................................
Epoch 20: loss 33.716087341308594, accuracy 64.05087592992561
....................................
Epoch 21: loss 33.403533935546875, accuracy 64.57883369330453
....................................
Epoch 22: loss 32.9720344543457, accuracy 65.49076073914087
....................................
Epoch 23: loss 32.635032653808594, accuracy 65.89872810175186
....................................
Epoch 24: loss 32.3167610168457, accuracy 65.53875689944805
....................................
Epoch 25: loss 32.33857345581055, accuracy 66.2107031437485
....................................
Epoch 26: loss 33.478424072265625, accuracy 64.48284137269019
....................................
Epoch 27: loss 31.90555191040039, accuracy 66.8106551475882
....................................
Epoch 28: loss 31.922758102416992, accuracy 66.04271658267339
....................................
Epoch 29: loss 31.769996643066406, accuracy 67.0026397888169
....................................
Epoch 30: loss 32.07068634033203, accuracy 66.09071274298056
....................................
Epoch 31: loss 31.733060836791992, accuracy 67.0026397888169
....................................
Epoch 32: loss 31.532672882080078, accuracy 67.14662826973841
....................................
Epoch 33: loss 31.78310203552246, accuracy 66.76265898728101
....................................
Epoch 34: loss 31.222070693969727, accuracy 67.170626349892
....................................
Epoch 35: loss 31.330495834350586, accuracy 66.57067434605231
....................................
Epoch 36: loss 31.010828018188477, accuracy 67.41060715142788
....................................
Epoch 37: loss 31.326351165771484, accuracy 67.14662826973841
....................................
Epoch 38: loss 31.47686195373535, accuracy 66.4026877849772
....................................
Epoch 39: loss 31.304813385009766, accuracy 66.9786417086633
....................................
Epoch 40: loss 31.42787742614746, accuracy 66.90664746820255
....................................
Epoch 41: loss 31.324193954467773, accuracy 66.49868010559155
....................................
Epoch 42: loss 30.773801803588867, accuracy 67.43460523158147
....................................
Epoch 43: loss 31.23522186279297, accuracy 67.12263018958484
....................................
Epoch 44: loss 30.887908935546875, accuracy 67.89056875449964
....................................
Epoch 45: loss 30.536348342895508, accuracy 67.3866090712743
....................................
Epoch 46: loss 30.796695709228516, accuracy 66.45068394528438
....................................
Epoch 47: loss 31.02267837524414, accuracy 67.24262059035277
....................................
Epoch 48: loss 30.272396087646484, accuracy 67.53059755219583
....................................
Epoch 49: loss 31.18903160095215, accuracy 66.52267818574514
....................................
Epoch 50: loss 30.27387237548828, accuracy 68.32253419726422
....................................
Epoch 51: loss 30.756324768066406, accuracy 67.81857451403887
....................................
Epoch 52: loss 30.106008529663086, accuracy 68.10655147588193
....................................
Epoch 53: loss 30.574302673339844, accuracy 67.67458603311735
....................................
Epoch 54: loss 30.22770881652832, accuracy 68.22654187664986
....................................
Epoch 55: loss 29.99200439453125, accuracy 68.65850731941444
....................................
Epoch 56: loss 30.453886032104492, accuracy 67.93856491480682
....................................
Epoch 57: loss 30.077186584472656, accuracy 68.34653227741781
....................................
Epoch 58: loss 30.0889892578125, accuracy 68.46652267818574
....................................
Epoch 59: loss 29.739351272583008, accuracy 68.82649388048956
....................................
Epoch 60: loss 30.448667526245117, accuracy 67.77057835373171
....................................
Epoch 61: loss 30.61048126220703, accuracy 67.67458603311735
....................................
Epoch 62: loss 29.84048080444336, accuracy 68.13054955603552
....................................
Epoch 63: loss 30.002206802368164, accuracy 68.87449004079673
....................................
Epoch 64: loss 30.04825782775879, accuracy 68.10655147588193
....................................
Epoch 65: loss 30.07265281677246, accuracy 68.65850731941444
....................................
Epoch 66: loss 29.8739070892334, accuracy 69.04247660187185
No loss decrease after 5 epochs
THCudaCheck FAIL file=c:\users\administrator\downloads\new-builder\win-wheel\pytorch\torch\csrc\generic\StorageSharing.cpp line=253 error=63 : OS call failed or operation not supported on this OS
Traceback (most recent call last):
File "D:/devkit_tracking/autokeras-0.2.1/examples/cifar10.py", line 9, in 
clf.fit(x_train, y_train, time_limit=12 * 60 * 60)
File "C:\Program Files\Python36\lib\site-packages\autokeras\classifier.py", line 225, in fit
run_searcher_once(train_data, test_data, self.path)
File "C:\Program Files\Python36\lib\site-packages\autokeras\classifier.py", line 40, in run_searcher_once
searcher.search(train_data, test_data)
File "C:\Program Files\Python36\lib\site-packages\autokeras\search.py", line 190, in search
accuracy, loss, graph = train_results.get()[0]
File "C:\Program Files\Python36\lib\multiprocessing\pool.py", line 644, in get
raise self._value
multiprocessing.pool.MaybeEncodingError: Error sending result: '[(68.56251499880008, tensor(29.9675, device='cuda:0'), <autokeras.graph.Graph object at 0x0000000019E90128>)]'. Reason: 'RuntimeError('cuda runtime error (63) : OS call failed or operation not supported on this OS at c:\users\administrator\downloads\new-builder\win-wheel\pytorch\torch\csrc\generic\StorageSharing.cpp:253',)'

Process finished with exit code 1

Reproducing Steps
Steps to reproduce the behavior:

Step 1: Follow the instruction steps for 0.2.1 install
Step 2: Run examples\cifar10.py

Expected Behavior
Run without error

Setup Details
Include the details about the versions of:

Windows7
Python: 3.6
autokeras: 0.2.1
scikit-learn: 0.19.1
numpy: 1.14.5
keras: 2.2.2
scipy: 1.1.0
tensorflow: 1.9.0
pytorch: 0.4.0 

Additional context
NULL

**Comment by xialulu826** [comment]
@jhfjhfj1 Thanks, the problem has been sloved,next time ,I will use the bug report to give my problem.
