### ISSUE TITLE
Error when loading a saved model

### ISSUE THREAD

**Issue by jeanjerome** [jhfjhfj1/autokeras#117]
Hi,

### Bug Description

After a training process where everything went fine, I've tried to load saved models but get this error 
```
 Using TensorFlow backend.
Traceback (most recent call last):
  File "../src/model_info.py", line 6, in <module>
    new_model = load_model('XXX/app-autokeras/model/4.h5')
  File "XXX/app-autokeras/tensorflow/lib/python3.6/site-packages/keras/engine/saving.py", line 249, in load_model
    f = h5py.File(filepath, mode='r')
  File "XXX/app-autokeras/tensorflow/lib/python3.6/site-packages/h5py/_hl/files.py", line 312, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "XXX/app-autokeras/tensorflow/lib/python3.6/site-packages/h5py/_hl/files.py", line 142, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (file signature not found)
```

### Reproducing Steps
  * Step 1: Train model with autokeras
  * Step 2: After the training process, run the script 
```
import tensorflow as th
from keras.models import load_model

if __name__ == '__main__':
	new_model = load_model('XXX/app-autokeras/model/4.h5')
	new_model.summary()
```

### Expected Behavior

Well, at least the model info :)

### Setup Details
Include the details about the versions of:
 - OS type and version: macOS High Sierra 10.13.6
 - Python: 3.6.5
 - autokeras: 0.2.3
 - scikit-learn: 0.19.1
 - numpy: 1.14.5
 - keras: 2.2.2
 - scipy: 1.1.0
 - tensorflow: 1.8.0
 - pytorch:

Thanks !

**Comment by jeanjerome** [comment]
Ok,

Think I have understood the Autokeras way. This code is loading a saved model.
1. Get the autokeras graph
2. Generate a keras model from the graph

```
import os
from autokeras.utils import pickle_from_file

if __name__ == '__main__':
	path = 'XXX/app-autokeras/model'
	searcher = pickle_from_file(os.path.join(path, 'searcher'))
	graph = searcher.load_best_model()
	best_model = graph.produce_keras_model()
	best_model.summary()
```

**Comment by jeanjerome** [comment]
More code examples would be appreciated.

Thanks for your work !

**Comment by crypdick** [comment]
@jeanjerome I get `AttributeError: 'Graph' object has no attribute 'produce_keras_model`. I don't see `produce_keras_model` anywhere in the codebase...
