### ISSUE TITLE
GeneralRegressor

### ISSUE THREAD

**Issue by michelleowen** [jhfjhfj1/autokeras#120]
### Suggested Name

Regression

### Task Description

A general regression problem with both numeric and categorical features. The input is tabular data.
The regression target is a single value for each input data which is a row in the table.

### Evaluation Metrics

Mean Square Error

### Benchmark Datasets

NA

### Reason

There are a lot of regression problems in machine learning 

### Solution

NA

### Additional Context

NA

**Comment by song3134** [comment]
#130 Thanks for the request. I'm currently working on these two issues.

**Comment by jhfjhfj1** [comment]
This issue is solved. Please see the code in the examples directory.

**Comment by Chowkah** [comment]
Does this rely on lightgbm only or cover DL architectures as well?

**Comment by theUniverseofData** [comment]
I can not find the GeneralRegressor in the documentation, or in the code examples

**Comment by joseph-allen** [comment]
can't find this either, seems to be issues with GeneralRegressor, TabularClassifier etc. but nothing in the codebase or docs.

**Comment by JacobZuliani** [comment]
> can't find this either, seems to be issues with GeneralRegressor, TabularClassifier etc. but nothing in the codebase or docs.



> I can not find the GeneralRegressor in the documentation, or in the code examples

AutoKeras Tabular was removed, reason for this is explained in #562 

Thankfully @bolkedebruin created a package (https://pypi.org/project/autokeras-tabular/) containing the missing functionality.
