### ISSUE TITLE
VideoRegressor

### ISSUE THREAD

**Issue by jhfjhfj1** [jhfjhfj1/autokeras#138]
### Suggested Name

VideoRegressor

### Task Description

Each training instance is a video clip. The target is a single real value.

### Evaluation Metrics

Mean Square Error

**Comment by jayavanth** [comment]
@haifeng-jin Is this feature available yet? Because I'm getting an error

`ValueError: Expect the data to ImageInput to have 3 or 4 dimensions, but got input shape (5000, 3, 360, 640, 3) with 5 dimensions
`
when I have more than 1 video frame

**Comment by haifeng-jin** [comment]
Sorry, this is not of high priority now. We may get to it later when we have finished the tasks in progress.
