### ISSUE TITLE
SpeechRecognition

### ISSUE THREAD

**Issue by jhfjhfj1** [jhfjhfj1/autokeras#142]
### Suggested Name

SpeechRecognition

### Task Description

Based on the audio input file, produce a text file.
The audio file is someone reading an article in English.
The produced text file should be the script.

### Evaluation Metrics

Accuracy

### Benchmark Datasets

[Librispeech](http://www.openslr.org/12/)

**Comment by hemanthsavasere** [comment]
Hi @jhfjhfj1, I would like to contribute. Is this issue assigned to someone?

**Comment by jhfjhfj1** [comment]
@hemanthsavasere This is a duplicated issue of #448 . Should be closed. sorry for the confusion. @boyuangong is working on this.
