### ISSUE TITLE
No module named 'tqdm'

### ISSUE THREAD

**Issue by HunbeomBak** [jhfjhfj1/autokeras#147]
### Bug Description
 1 import autokeras as ak

~/anaconda3/lib/python3.6/site-packages/autokeras/__init__.py in <module>()
----> 1 from autokeras.image_supervised import ImageClassifier, ImageRegressor

~/anaconda3/lib/python3.6/site-packages/autokeras/image_supervised.py in <module>()
     17 from autokeras.metric import Accuracy, MSE
     18 from autokeras.preprocessor import OneHotEncoder, DataTransformer
---> 19 from autokeras.search import Searcher, train
     20 from autokeras.utils import ensure_dir, has_file, pickle_from_file, pickle_to_file, temp_folder_generator
     21 

~/anaconda3/lib/python3.6/site-packages/autokeras/search.py in <module>()
      8 from autokeras.generator import CnnGenerator
      9 from autokeras.net_transformer import default_transform
---> 10 from autokeras.utils import ModelTrainer, pickle_to_file, pickle_from_file
     11 
     12 import torch.multiprocessing as mp

~/anaconda3/lib/python3.6/site-packages/autokeras/utils.py in <module>()
     10 
     11 from autokeras.constant import Constant
---> 12 from tqdm.autonotebook import tqdm
     13 
     14 class NoImprovementError(Exception):

ModuleNotFoundError: No module named 'tqdm'

### Reproducing Steps
  * Step 1: install autokeras with 'sudo pip3 install autokeras' in ubuntu 16.04 terminal
  * Step 2: operate jupyter notebook, then run 'import autokeras as ak'

### Setup Details
Include the details about the versions of:
 - OS type and version: ubuntu 16.04
 - Python: 
 - autokeras: 0.2.8
 - scikit-learn:
 - numpy:
 - keras:
 - scipy:
 - tensorflow:
 - pytorch:

### Additional context

same problem in Google Colab

**Comment by song3134** [comment]
Fixed in the new release. Please reopen the issue if it remains unsolved. Thx.
