### ISSUE TITLE
pip install autokeras   fails on Win 10, 64.

### ISSUE THREAD

**Issue by cpoptic** [jhfjhfj1/autokeras#148]
### Reproducing Steps
  * Step 1: ... at CMD prompt, type  `pip install keras`
  * Step 2: ... 

> Collecting autokeras

> Using cached https://files.pythonhosted.org/packages/15/c9/6aafd8b03a2fe2c0d018fb6b37263caa4980e391edb8f1bae05c6bcc785b/autokeras-0.2.9.tar.gz

>     Complete output from command python setup.py egg_info:
>     error in autokeras setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Invalid requirement, parse error at "'=4.25.0'"
> 

### Setup Details
Include the details about the versions of:
 - OS type and version:  Windows 10, 64-bit
 - Python: 3.6.6
 - autokeras: 
 - scikit-learn:  0.19.0
 - numpy:  1.15.1
 - keras:  2.2.2
 - scipy:  0.19.1
 - tensorflow:  1.10.0
 - pytorch:

**Comment by HunbeomBak** [comment]
Same error on Google Colab.
In Colab, run '!pip install autokeras'. Then, 
Complete output from command python setup.py egg_info:
    error in autokeras setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Invalid requirement, parse error at "'=4.25.0'"

**Comment by jhfjhfj1** [comment]
@cpoptic @HunbeomBak Thank you for the feedback.
It has just been solved in the new release of 0.2.10.

Thanks.

**Comment by cpoptic** [comment]
>  Could not find a version that satisfies the requirement tensorflow>=1.10.1 (from autokeras) (from versions: 1.2.0rc2, 1.2.0, 1.2.1, 1.3.0rc0, 1.3.0rc1, 1.3.0rc2, 1.3.0, 1.4.0rc0, 1.4.0rc1, 1.4.0, 1.5.0rc0, 1.5.0rc1, 1.5.0, 1.5.1, 1.6.0rc0, 1.6.0rc1, 1.6.0, 1.7.0rc0, 1.7.0rc1, 1.7.0, 1.7.1, 1.8.0rc0, 1.8.0rc1, 1.8.0, 1.9.0rc0, 1.9.0rc1, 1.9.0rc2, 1.9.0, 1.10.0rc0, 1.10.0rc1, 1.10.0)
No matching distribution found for tensorflow>=1.10.1 (from autokeras)

**Comment by AvinoamK** [comment]
Lasr tensorfloaw version is 1.10.0, and there is no 1.10.1 yet
