### ISSUE TITLE
pip install autokeras fails:  "No matching distribution found for tensorflow>=1.10.1 (from autokeras)"

### ISSUE THREAD

**Issue by cpoptic** [jhfjhfj1/autokeras#151]
### Reproducing Steps
  * Step 1: ... at CMD prompt, type pip install keras
  * Step 2: ...

### Setup Details
Include the details about the versions of:
OS type and version: Windows 10, 64-bit
Python: 3.6.6
autokeras:
scikit-learn: 0.19.0
numpy: 1.15.1
keras: 2.2.2
scipy: 0.19.1
tensorflow: 1.10.0
pytorch:  0.4.1

Hmm, when I run `conda list` it shows tensorflow 1.7.0 and tensorflow-gpu 1.7.0
I then ran `pip install -U tensorflow`   and `pip install -U tensorflow-gpu`  to upgrade both to version 1.10.0 and then re-ran `pip install autokeras`

**Comment by jhfjhfj1** [comment]
I will release a new version of autokeras using tensorflow 1.10.0 instead.
Thanks.
@cpoptic

**Comment by devanshuDesai** [comment]
@jhfjhfj1 it's mid-November and I still seem to have this issue
