### ISSUE TITLE
load_raw_image.zip example is broken

### ISSUE THREAD

**Issue by dietercastel** [jhfjhfj1/autokeras#152]
### Bug Description
The load_raw_image example in the load_raw_image.zip under examples still contains the old naming convention:

```from autokeras.classifier import load_image_dataset```

While the current (and working) example in the github pages reads:

```from autokeras.image_supervised import load_image_dataset```

### Reproducing Steps
  * Step 1: Download zip and extract
  * Step 2: See for yourself

### Expected Behavior
A working example on download :-)

Might I suggest removing the code from the zip file and just placing it on git. So it can more easily be spotted and updated. Since I assume the image files will remain the same leaving them in a zip makes sense I guess.

**Comment by dietercastel** [comment]
I might fix this myself tomorrow if you agree with my proposed solution or provide a better suggestion.

**Comment by jhfjhfj1** [comment]
@dietercastel Thank you so much!
You can go ahead a fix it.
