### ISSUE TITLE
load_image_dataset can not deal with different size image.

### ISSUE THREAD

**Issue by supermanhuyu** [jhfjhfj1/autokeras#153]
when my images size are not same , the  load_image_dataset function can not be deal to  the numpy arrays what we can use directly .

**Comment by jhfjhfj1** [comment]
@supermanhuyu 
Thank you for the feedback.
Currently, we do not support images of different sizes.
Will consider support it later.

**Comment by dietercastel** [comment]
I noticed this too. As a temporary quick and dirty solution you can patch read_images in image_supervised.py as follows:

```python
#In images_supervised.py of your autokeras lib
# Add the necessary import to the top of the file:
from scipy.misc import imresize
#...
def read_images(...): 
#...
# after this line:
     img = ndimage.imread(fname=img_path)
# add this with (299,299) the size to resize too.
     img = imresize(img,(299,299)) # use scipy imresize to resize all images
# rest of the read_images function
     if len(img.shape) <3:
#...
```

I'm wondering what a more general way of solving this issue would look like though. Looking for the smallest image in the images and scaling all other to that size maybe?

**Comment by supermanhuyu** [comment]
@dietercastel  thank you . i have defined a function to instead of the load_image_dataset function, looks like your comment.

**Comment by zuoxiang95** [comment]
hello @dietercastel , I have tried your solution, use scipy imresize to resize all images, but i have got a error:
  File "train.py", line 54, in read_images
    return np.asanyarray(x_train)
  File "/home/zuoxiang/anaconda3/envs/tensorflow/lib/python3.6/site-packages/numpy/core/numeric.py", line 544, in asanyarray
    return array(a, dtype, copy=False, order=order, subok=True)
ValueError: could not broadcast input array from shape (416,416,3) into shape (416,416)

here is my code:
`
def read_images(img_file_names, images_dir_path):
    """Read the images from the path and return their numpy.ndarray instance.
        Return a numpy.ndarray instance containing the training data.
    Args:
        img_file_names: List containing images names.
        images_dir_path: Path to the directory containing images.
    """
    x_train = []
    if os.path.isdir(images_dir_path):
        for img_file in img_file_names:
            img_path = os.path.join(images_dir_path, img_file)
            if os.path.exists(img_path):
                img = ndimage.imread(fname=img_path)
                img = imresize(img, (416,416))
                if len(img.shape) < 3:
                    img = img[..., np.newaxis]
                x_train.append(img)
            else:
                raise ValueError("%s image does not exist" % img_file)
    else:
        raise ValueError("Directory containing images does not exist")
    return np.asanyarray(x_train)
`

**Comment by dietercastel** [comment]
I suspect you're using a different version of scipy (1.0.0 or greater) than the one autokeras actually uses. Do you import from`imread` from `imageio`?

Autokeras actually uses the deprecated `scipy.misc.imread` instead of the current `imageio.imread`. Going forward I think it's best to upgrade.

The dirty fix I proposed was also based on the deprecated version `scipy.misc.imread`.
