### ISSUE TITLE
Creating a online crowd funding campaign

### ISSUE THREAD

**Issue by hemangjoshi37a** [jhfjhfj1/autokeras#164]
`feature_request`

### Feature Description
About creating a online crowd funding campaign for this project to help the project financially and let you hire people for this project.

### Reason
Your idea is great and will create some awesome open source project and I want to help you.

### Solution
Hire me as your assistant for crowd funding on online websites and from different sources. It will help you get some financial help and hire some people who can help us creating some more code for this project.
I have past experience working with [KickStarter](http://kickstarter.com) and [Indigogo](https://www.indiegogo.com). I  also have PayPal business account to transfer funds online from the campaign websites to you.

### Alternative Solutions
You can just say no to this feature request that is alternative option but not in favor of us LOL.

### Why Am I interested?
Actually I am currently working on a similar idea which is at very initial stage. I am adding GUI to help build ML script where yours is totally automated but scripted. You can take a look at my repo : [GeneralML](https://github.com/hemangjoshi37a/genearalML). I have created a donate button for my project you can take a look at the read me section on this repository [page](https://github.com/hemangjoshi37a/genearalML).

### Additional Context
My LinkedIn profile : [Hemang Joshi](https://www.linkedin.com/in/hemang-joshi-046746aa)
My Kaggle profile : [Hemang Joshi](https://www.kaggle.com/hemangjoshi37a)

### Fun fact
I got admit from Texas A&M at Kingsville for PG student in Electrical Engineer in 2016 but I was not able to get visa at the time Trump Election.

I hope for positive response from you.

Thank you and regards,
Hemang Joshi

**Comment by jhfjhfj1** [comment]
@hemangjoshi37a 
Thank you for your suggestions!
This project is currently running in our university.
I am not sure whether we would hire anyone at the current stage.

We are very open to any financial suggestions.
What do you think of opencollective?
Or is there any crowdfunding websites just for open source projects?

**Comment by LemonAndroid** [comment]
@jhfjhfj1 open collective looks good.

**Comment by hemangjoshi37a** [comment]
@jhfjhfj1 sir,
As you said that you are running this project from a university which i didn't knew, and if so that you would be getting good financial aid from the university itself. I thought that you are a Ph.D. student LOL.
But anyway still you want some financial aid then you can try KickStarter and Indigogo crowd funding websites.
And I have sent my resume if there is any recruitment or something like that. Please let me know if there is any.

**Comment by LemonAndroid** [comment]
@jhfjhfj1 

Just remembered you asked about open-source-exclusive platforms for recurring crowd funding.

There is salt.bountysource.com, which is also open source and only used by open source projects.
