### ISSUE TITLE
Link to this repo from https://autokeras.com/ is broken

### ISSUE THREAD

**Issue by dmartinez05** [jhfjhfj1/autokeras#172]
### Bug Description
The link at https://autokeras.com/ to this repo is broken.

### Reproducing Steps
  * Step 1: Go to https://autokeras.com/
  * Step 2: Click into `Edit on GitHub`

**Comment by TheoKlein** [comment]
Right now `mkdocs/docs/index.md` is generated dynamically. It's not actually placed in the repository.

MkDocs's [official repository](https://github.com/mkdocs/mkdocs/) is a good demonstration. Maybe we should just put all the docs in one place.
