### ISSUE TITLE
Is it like Google AutoML?

### ISSUE THREAD

**Issue by theprodev** [jhfjhfj1/autokeras#174]
Hi, I am a newbie in ML specially deep learning, Whatever I learned about your repo on towardsdatascience is very interesting. Is it like posting my images somewhere and it will automatically give me a rest api to classify my future images? That is what Google AutoML as far as I understand. But your AutoML seems different? Is it something else? 

How can I run a server? In a docker instance? and post my images of different classes? and get a trained model in return? or an inference server which I can use via REST API?

I myself made a pipeline where I can upload a zip file of images split in train, test and valid folders and get a running server which I can call via REST and get prediction in JSON. Did I accidentally made AutoML? (smile).  I am not sure. 

Your reply will be highly appreciated.

Thanks.

Note: I see some simple examples using pre-trained models for object detection and classification in Gluon docs. These are very helpful. Please add some simple tutorials to describe your work if possible.

**Comment by sebastianheinz** [comment]
Nope, Autokeras is a Python library without any graphical user interface. If you want to expose your model as an API, you have to build it in Python yourself. I am not sure what exactly you built in your pipeline but it seems to go in a similar direction as AutoML. I wrote a [blog post about Google AutoML](https://www.statworx.com/de/blog/a-performance-benchmark-of-google-automl-vision-using-fashion-mnist/) that you might find useful understanding the functionalities.
