### ISSUE TITLE
[bug report] No such file or directory: '/tmp/autokeras/searcher'

### ISSUE THREAD

**Issue by EricDoug** [jhfjhfj1/autokeras#183]
### Bug Description
I am running the demo in Jupyter notebook from  the [Getting Started page](https://autokeras.com/start/), but get the error of  `FileNotFoundError: [Errno 2] No such file or directory: '/tmp/autokeras/searcher'`, and the code as fellow:

FileNotFoundError: [Errno 2] No such file or directory: '/tmp/autokeras/searcher'

```python
import os
from autokeras.image_supervised import load_image_dataset
from autokeras import ImageClassifier
```

```python
mnistRoot = "/home/dl/autokeras/src/autokeras/examples/load_raw_image"
trainDir = os.path.join(mnistRoot, "train")
trainLabel_file = os.path.join(trainDir, "label.csv")
testDir = os.path.join(mnistRoot, "test")
testLabel_file = os.path.join(testDir, "label.csv")
```

```python
x_train, y_train = load_image_dataset(csv_file_path=trainLabel_file,
                                      images_path=trainDir)
print(x_train.shape)
print(y_train.shape)
```

    (60000, 28, 28, 1)
    (60000,)

```python
x_test, y_test = load_image_dataset(csv_file_path=testLabel_file,
                                    images_path=testDir)
print(x_test.shape)
print(y_test.shape)
```

    (10000, 28, 28, 1)
    (10000,)

```python
clf = ImageClassifier(verbose=True, augment=False)
```

```python
modelRoot = "/home/champion/models"
autokerasModel = os.path.join(modelRoot, "autokeres")
mnist_model = os.path.join(autokerasModel, "mnist_model.h5")
```

```python
clf.load_searcher().load_best_model().produce_keras_model().save(mnist_model)
```

    ---------------------------------------------------------------------------

    FileNotFoundError                         Traceback (most recent call last)

    <ipython-input-22-ac36f5c7f33f> in <module>()
    ----> 1 clf.load_searcher().load_best_model().produce_keras_model().save(mnist_model)
    

    ~/venv/lib/python3.6/site-packages/autokeras/image_supervised.py in load_searcher(self)
        292 
        293     def load_searcher(self):
    --> 294         return pickle_from_file(os.path.join(self.path, 'searcher'))
        295 
        296     def final_fit(self, x_train, y_train, x_test, y_test, trainer_args=None, retrain=False):

    ~/venv/lib/python3.6/site-packages/autokeras/utils.py in pickle_from_file(path)
        214 
        215 def pickle_from_file(path):
    --> 216     return pickle.load(open(path, 'rb'))
        217 
        218 

    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/autokeras/searcher'

### Setup Details
Include the details about the versions of:
 - OS type and version:  Ubuntu 16.04
 - Python:  3.6.5
 - autokeras:   master

**Comment by uditjuneja1** [comment]
The code maybe is trying to import Searcher form autokeras/search.

**Comment by jhfjhfj1** [comment]
This is resolved in the current version. Thanks.
