### ISSUE TITLE
Example code and Tutorial

### ISSUE THREAD

**Issue by theprodev** [jhfjhfj1/autokeras#185]
https://autokeras.com/start/#what-if-your-data-are-raw-image-files-eg-jpg-png-bmp

I am trying this but fit method is not working. Actually I do not find the example for fit method when doing raw images. I think if you add a few lines, it will be complete code from loading data set to model export.

Thanks for your help.

**Comment by jhfjhfj1** [comment]
@theprodev 
Thank you for your interest.
We will update the tutorial later.

**Comment by jhfjhfj1** [comment]
@boyuangong Please add the tutorial for the image, text and the cnn_module, MLP module (In progress) to the documentation, with example code. Thanks.
