### ISSUE TITLE
怎么使用这个工程

### ISSUE THREAD

**Issue by 1789120321** [jhfjhfj1/autokeras#188]

**Comment by jhfjhfj1** [comment]
Please follow the instructions on our website, autokeras.com

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by minda163** [comment]
@1789120321  请问你知道这个工程的使用方法了吗，有没有教程？看官网上的东西，还是不全面，很多语句不知道怎么用。
