### ISSUE TITLE
GPU usage

### ISSUE THREAD

**Issue by impulsecorp** [jhfjhfj1/autokeras#19]
Your /examples/mnist.py  does not load GPUtil like your older experiments files do (like
https://github.com/jhfjhfj1/autokeras/blob/master/experiments/mnist.py ). Does it no longer need GPUtil? 
It was not on your requirements.txt list.

This is what I am talking about:
-----------------------------------------------
import os
import GPUtil

def select_gpu():
    try:
        # Get the first available GPU
        DEVICE_ID_LIST = GPUtil.getFirstAvailable()
        DEVICE_ID = DEVICE_ID_LIST[0]  # grab first element from list

        # Set CUDA_VISIBLE_DEVICES to mask out all other GPUs than the first available device id
        os.environ["CUDA_VISIBLE_DEVICES"] = str(DEVICE_ID)
    except FileNotFoundError:
print("GPU not found")

**Comment by xuzhang5788** [comment]
Even I included GPUtil, I still can not select my GPU.

**Comment by AtomicJosh** [comment]
Same here, I couldn't get it to recognize my GPU.

**Comment by jhfjhfj1** [comment]
Thank you all for the report.
The current version is using pytorch.
I am not sure it can support selecting GPU or not.

If really in need of selecting GPU, please submit a new issue with feature request template.
Thank you.
