### ISSUE TITLE
Dynamic memory limitation is disfunctional

### ISSUE THREAD

**Issue by swenkel** [jhfjhfj1/autokeras#191]
### Bug Description

[#180](https://github.com/jhfjhfj1/autokeras/pull/180) should have solved the ```CUDA out of memory``` problem. However, during training (```clf.fit```) it will simply output the current model it wants to train and that it is out of memory. This message is repeated until the time limit is reached:

```
╒==============================================╕
|              Training model 6                |
╘==============================================╛
out of memory
```

While displaying this , autokeras will try to load the model into memory again and will break down againg caused this message.

### Expected Behavior

- building smaller models
- limit the memory more agrressively
- or: sequential CUDA memory allocation and deallocation
### Setup Details
Include the details about the versions of:
 - OS type and version:
 - Python: 
 - autokeras: develop (todays version from 06:00 UTC)
 - scikit-learn:
 - numpy:
 - keras:
 - scipy:
 - tensorflow:
 - pytorch:

### Additional context

dataset used: subset of the [German Traffic Sign Recognition Benchmark](http://benchmark.ini.rub.de/?section=gtsrb&subsection=news)

**Comment by jhfjhfj1** [comment]
@swenkel Thanks. This is the expected behavior. Whenever it is out of memory, it would never search such large models, but smaller ones.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
