### ISSUE TITLE
MLPRegressor and MLPClassifier

### ISSUE THREAD

**Issue by jcpeterson** [jhfjhfj1/autokeras#194]
These are basic and should be included

**Comment by jhfjhfj1** [comment]
@jcpeterson Thanks.
Currently, we only opened task-specific interfaces.
We will be extracting the network-type level interfaces soon.

**Comment by jcpeterson** [comment]
Cool, any idea on the approximate timeline?

**Comment by jhfjhfj1** [comment]
It is supported. You can check the tutorials on autokeras.com.
