### ISSUE TITLE
Parameter Usage

### ISSUE THREAD

**Issue by impulsecorp** [jhfjhfj1/autokeras#20]
How do I use the parameters? If I use
 clf = ImageClassifier(verbose=True, searcher_args={'trainer_args': {'max_iter_num': 10, 'augment': False}, 'default_model_len': 3})

I get this error:    TypeError: __init__() got an unexpected keyword argument 'searcher_args'

**Comment by jhfjhfj1** [comment]
Thank you for your report.
This is fixed in the latest release.

Please reopen the issue if it is not.
