### ISSUE TITLE
Specify the validation set in the parameters of fit()

### ISSUE THREAD

**Issue by Zvezdin** [jhfjhfj1/autokeras#209]
### Feature Description
In supervised.py:

`fit(self, x_train=None, y_train=None, time_limit=None):`
to
`fit(self, x_train=None, y_train=None, x_test=None, y_test=None, time_limit=None):`

And then update the implemented task modules to use the test subset (if provided) instead of splitting the train.

### Reason

In some cases the automatic split of 80:20 (in the case of ImageSupervised) is not good enough and the model has to be evaluated on a specific subset which is already available.

### Solution
I can submit a pull request if you consider this as a needed feature. I'd argue that it doesn't increase the complexity of using the project in its simplest form since the old automatic splitting is also preserved.

### Alternative Solutions
Leave it as it is.

**Comment by tl-yang** [comment]
Hi @Zvezdin,
    Thanks for the idea. It's indeed needed for maximum flexibility. However, we're trying to refactor the whole structure now, so we may have to wait a little bit.

**Comment by agnz** [comment]
I don't see this functionality in the latest version. Was it taken out again for some reason?
