### ISSUE TITLE
"numpy.linalg.linalg.LinAlgError: N-th leading minor of the array is not positive definite" exception while training ImageClassifier

### ISSUE THREAD

**Issue by Zvezdin** [jhfjhfj1/autokeras#212]
### Bug Description

When training ImageClassifier on float inputs of shape 80x92x24 on a binary classification task, this exception is thrown when AutoKeras lists all created models until this point and their respected losses and metrics. Here is a more complete log + stack trace:  http://termbin.com/gb3n

### Reproducing Steps

* Create a dataset of noise shaped 80x92x24 with ~360 or so samples
*  Respective binary labels.

In my case, some values of the dataset are quite large (they vary between 0 and 1_000_000, but I'm not sure that this is related since AutoKeras performs normalization).

* Have it train on a GTX 1070Ti or equivalent in terms of vram for about an hour (can't confirm that it's GPU-related either).
* Wait for the exception

### Expected Behavior

It should work.

### Setup Details
 - OS type and version: Ubuntu 18.04
 - Python: 3.6
 - autokeras: 0.2.14 (installed manually from git)
- all dependencies are installed as stated in requirements.txt for this release, unless for:
- tensorflow 1.10, compiled locally.

**Comment by jhfjhfj1** [comment]
@Zvezdin Thank you for the report.
I think this has been fixed in the develop branch.
Will be released soon.
