### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by wenyawei** [jhfjhfj1/autokeras#218]
### Reproducing Steps
I run autokeras with my own dataset, and the size is:
```
(196, 60, 60, 3)
(196,)
```
When I run it after 205 models, it CANNOT create new model to run. The log is 
```
╒==============================================╕
|              Training model 205              |
╘==============================================╛
/home/adt/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
                                                                           out of memory
/home/adt/anaconda3/lib/python3.6/multiprocessing/semaphore_tracker.py:143: UserWarning: semaphore_tracker: There appear to be 1 leaked semaphores to clean up at shutdown
  len(cache))
```

My GPU is GTX 1080Ti, and the memory is 12GB.

### Setup Details
Include the details about the versions of:
 - OS type and version: Ubuntu 1804
 - Python:  3.6
 - autokeras: 
 - scikit-learn: 0.19.1
 - numpy: 1.14.5
 - keras: 2.22
 - tensorflow: 1.10
 - pytorch: 0.41

**Comment by rafaelmarconiramos** [comment]
I receive the same error, but on Model 1. I never reach more than two models. 
I read here that maybe the problem is the autokeras generates heavy models to try.

**Comment by jhfjhfj1** [comment]
@wenyawei Thank you for your report.
It is an expected behavior.
It would affect the search too much.

Thanks.
