### ISSUE TITLE
pip install autokeras fails on torch==0.4.1

### ISSUE THREAD

**Issue by bersbersbers** [jhfjhfj1/autokeras#219]
### Reproducing Steps
`pip install autokeras`

### Expected Behavior
Installs autokeras. Instead:

```
Collecting autokeras
  Using cached https://files.pythonhosted.org/packages/d6/41/4f6d30a3e0d4b4ed89a01902a713243d6878c6cb452c32c777dcc68d5f4d/autokeras-0.2.15.tar.gz
Collecting torch==0.4.1 (from autokeras)
  Could not find a version that satisfies the requirement torch==0.4.1 (from autokeras) (from versions: 0.1.2, 0.1.2.post1)
No matching distribution found for torch==0.4.1 (from autokeras)
```

### Setup Details
Include the details about the versions of:
 - OS type and version: Windows 10
 - Python: Python 3.6.6
 - autokeras: 0.2.15
 - scikit-learn: not installed
 - numpy: numpy==1.15.2
 - keras: Keras==2.1.6, Keras-Applications==1.0.5, Keras-Preprocessing==1.0.3
 - scipy: scipy==1.1.0
 - tensorflow: tensorflow-gpu==1.11.0rc1, tensorboard==1.10.0
 - pytorch: not installed

**Comment by rafaelmarconiramos** [comment]
Install first the torch.
In my environment I installed ./torch-0.4.1-cp36-cp36m-manylinux1_x86_64.whl

**Comment by bersbersbers** [comment]
I see, thanks. Isn't PyTorch an alternative to TensorFlow? Do both need to be installed at the same time?
Furthermore, it is unfortunate that autokeras installes tensorflow, even though tensorflow-gpu is installed. Is this intended?

**Comment by jhfjhfj1** [comment]
@bersbersbers 
Installing tensorflow is needed for autokeras.
But there is no need to install it if tensorflow-gpu is installed.
We don't know how to determine whether tensorflow-gpu is installed in setup.py, so we just install tensorflow in all the situations.

**Comment by bersbersbers** [comment]
This (unresolved) issue may be relevant:
https://github.com/tensorflow/tensorflow/issues/7166

**Comment by hemangjoshi37a** [comment]
Download .whl package of torch 0.4.1 from any website and install it manually. It works fine.
