### ISSUE TITLE
How to load the trained model

### ISSUE THREAD

**Issue by marooncn** [jhfjhfj1/autokeras#222]
@jhfjhfj1 Hi, I have trained a .h5 model file successfully, how could I load the model to ak.ImageClassifier(). Thank you.

**Comment by jhfjhfj1** [comment]
Hi @marooncn 
I don't think we have this feature yet.
Would you please describe why you need to loaded with autokeras instead of directly use Keras?

Thanks.

**Comment by marooncn** [comment]
@jhfjhfj1 I just want to reload and compute the precision again, it's not a big deal. And there is one more question, does the searched model have randomness ? I run it twice and the results are different.
