### ISSUE TITLE
Out of memory in my small dataset

### ISSUE THREAD

**Issue by rafaelmarconiramos** [jhfjhfj1/autokeras#223]
### Bug Description
I executed an original example and works.
I change the example to my small dataset to try, but the search starts and stops on Training Model 1. It works to load the dataset, execute the first model, then stop in the second model and it still unsuccessful trying repeatedly.

I put in the searcher.train() a code to release memory suggest on #76, but didn´t work.

### Reproducing Steps
The log of my execution:
Using TensorFlow backend.
(43, 512, 512, 4)
(43,)
(46, 512, 512, 4)
(46,)

Initializing search.
Initialization finished.

+----------------------------------------------+
|               Training model 0               |
+----------------------------------------------+
totalMemory: 15.90GiB freeMemory: 15.27GiB
.........

Saving model.
+--------------------------------------------------------------------------+
|        Model ID        |          Loss          |      Metric Value      |
+--------------------------------------------------------------------------+
|           0            |   3.3943511486053466   |          0.5           |
+--------------------------------------------------------------------------+

+----------------------------------------------+
|               Training model 1               |
+----------------------------------------------+
totalMemory: 15.90GiB freeMemory: 15.27GiB
out of memory: 4198245
........

### Expected Behavior
I expected the process didn´t stop and stilled searching the architecture.

### Setup Details
Include the details about the versions of:
 - OS type and version:
 - Python: 3.6.2
 - autokeras: 0.2.14
 - scikit-learn: 0.19.1
 - numpy: 1.14.5
 - keras: 2.2.2
 - scipy: 1.1.0
 - tensorflow: 1.10.1
 - tensorflow-gpu: 1.3.0
 - torch: 0.4.1

### Additional context
This problem is a bug of implementation or the autokeras generate a heavy models and don´t get trainng?

**Comment by zuoxiang95** [comment]
i get the same error too, it seems the bug is not fixed.

**Comment by jhfjhfj1** [comment]
@rafaelmarconiramos @zuoxiang95 
This is an expected behavior.
It would affect the search too much, but continue to search smaller models.

**Comment by erichhhhho** [comment]
@jhfjhfj1 I got the same error in my custom dataset, saying out of memory in the second model and stop searching.

> 
                                                                           
                                                                           out of memory


╒==============================================╕
|               Training model 1               |
╘==============================================╛
Using TensorFlow backend.

                                                                           
                                                                           out of memory


╒==============================================╕
|               Training model 1               |
╘==============================================╛
Using TensorFlow backend.

                                                                           
                                                                           out of memory


╒==============================================╕
|               Training model 1               |
╘==============================================╛
Using TensorFlow backend.
