### ISSUE TITLE
Don't we use oneHot in this source?

### ISSUE THREAD

**Issue by ganav** [jhfjhfj1/autokeras#23]
Hey mr

i got following error (the code is from classifier.py in this source):

if x_train.shape[0] != y_train.shape[0]:
        raise ValueError('x_train and y_train should have the same number of instances.')

where x_train.shape is 972 but y_train.shape is 48600 which is 50 times than x_train.
because, i have 50 classes, so the oneHot gives me array of 50 numbers ([0, 0, 1, 0 .....0]) per image.

**Comment by jhfjhfj1** [comment]
Sorry for the late reply.
Auto Keras will encode the labels in y for you.
Y should be a one-dimensional array which has the same length as x.

Thanks.
