### ISSUE TITLE
Current model size is too big. Discontinuing training this model to search for other models.

### ISSUE THREAD

**Issue by dhlee-jubilee** [jhfjhfj1/autokeras#236]
Hi. I'm trying to apply autoKeras on own datasets. The dataset size is (1380, 299, 299, 3), but it's not working with "Current model size is too big. Discontinuing training this model to search for other models." error.

So, I resized images almost half, (1380, 128, 128, 3) and then tried again.
However, it was working initially, but the moment of training 9th model, the same error again.

What's the problem? What's the limitation of model size?

**Comment by rafaelmarconiramos** [comment]
I had the same problem.
This error is "out of memory problem."
The searcher creates a very complex model, and don´t get to put to execute on GPU.
I didn't find a solution. If you find, share with us.

**Comment by jhfjhfj1** [comment]
@dhlee-jubilee @rafaelmarconiramos 
This is a expected behavior. It should not affect the search.
Thanks.

**Comment by exowanderer** [comment]
@jhfjhfj1 Could you elaborate?

Your statement implies "this error is generated by autokeras", which is obvious. Your statement does not imply that this error is good or bad.

Does this mean that the model is not finding a good search criterion and that we should stop the algorithm / modify our data?  

Or does it mean that the algorithm is working as expected and we should continue.

thank you

**Comment by alessandropadrinofficial** [comment]
@jhfjhfj1  got the same problem as @exowanderer !

**Comment by alpha358** [comment]
Could someone suggest a way to implement a network size constraint in the tree search procedure ?
autokeras/search.py

Additional condition before adding to training_queue may suffice ?

```python
  if not self.training_queue:
                searched = True

                while new_father_id is None:
                    remaining_time = timeout - (time.time() - start_time)
                    new_graph, new_father_id = self.bo.optimize_acq(self.search_tree.adj_list.keys(),
                                                                    self.descriptors,
                                                                    remaining_time)
                new_model_id = self.model_count
                self.model_count += 1
                self.training_queue.append((new_graph, new_father_id, new_model_id))
                self.descriptors.append(new_graph.extract_descriptor())
```

**Comment by mlaradji** [comment]
I am facing the same problem and it seems to be an infinite loop. In 'search.py', we have the following:
```
        except RuntimeError as e:
            if not re.search('out of memory', str(e)):
                raise e
            if self.verbose:
                print('\nCurrent model size is too big. Discontinuing training this model to search for other models.')
            Constant.MAX_MODEL_SIZE = graph.size() - 1
            print(Constant.MAX_MODEL_SIZE) # Not in original file.
            return
```
As shown above, I have added a `print(Constant.MAX_MODEL_SIZE)`, which showed me that `Constant.MAX_MODEL_SIZE` stays constant (because `graph.size()` does not change) after each iteration of `Current model size is too big. Discontinuing training this model to search for other models.`. 

I'm unsure whether it's a mistake in the code or on my part, but it seems that `Constant.MAX_MODEL_SIZE` should be reduced everytime there was not enough memory to load a model, for example by having `Constant.MAX_MODEL_SIZE = max(1, round(Constant.MAX_MODEL_SIZE/2))` instead of `Constant.MAX_MODEL_SIZE = graph.size() - 1`.

**Comment by qmpzzpmq** [comment]
> Constant.MAX_MODEL_SIZE = max(1, round(Constant.MAX_MODEL_SIZE/2))

I had this same problem, it seems `graph.size()` should be reduced under `Constant.MAX_MODEL_SIZE`, but it didn't.

**Comment by JaeDukSeo** [comment]
very interesting

**Comment by JaeDukSeo** [comment]
https://www.simonwenkel.com/2018/09/05/autokeras-german-traffic-sign-recognition-benchmark.html
maybe this can help
