### ISSUE TITLE
Refactor searcher 

### ISSUE THREAD

**Issue by tl-yang** [jhfjhfj1/autokeras#245]
### Feature Description
Refactor searcher to be able to easily extend search algorithm to different method.

### Reason
Search algortihm other than Bayesian Optimization may be useful, too.

### Solution
Need more discussion with @jhfjhfj1

**Comment by mlaradji** [comment]
I'm interested in working on this. Perhaps we could integrate `hyperopt`, `Chocolate`, or `Advisor` (which combines `hyperopt` and `Chocolate` in its own API) into `autokeras`.

**Comment by chengchengeasy** [comment]
I will take care of this.

**Comment by jhfjhfj1** [comment]
Hi @tl-yang, I will assign this issue to @chengchengeasy.
He has already implemented a greedy algorithm.
You can focus on other issues.
