### ISSUE TITLE
PyTorch Model for Audio Classification

### ISSUE THREAD

**Issue by droidadroit** [jhfjhfj1/autokeras#248]
### Suggested Name

AudioClassifier

### Task Description

Create a PyTorch Model that classifies an audio into a genre. Do this for the UrbanSound and GTZAN datasets.

### Evaluation Metrics

TBD

**Comment by jhfjhfj1** [comment]
@droidadroit Thanks.
You can try to follow our code review video last time to get familiar with the code, and we can have a meeting next Monday after the code review to see how to integrate your part into the code base.

**Comment by gabrielgrant** [comment]
Did this actually get added at some point? Not seeing anything in the docs about it, nor immediately seeing any references in the code (though there does seem to be an older issue regarding the same feature: #132 )
