### ISSUE TITLE
Final fit not replacing the model in training history

### ISSUE THREAD

**Issue by twprinston** [jhfjhfj1/autokeras#249]
Hi,

if I run clf.final_fit(x_train, y_train, x_test, y_test, **retrain=True**)
then call
model = clf.load_searcher().**load_best_model()**.produce_keras_model()
Is this model the retrained model?

I traced the 0.2.18 ImageSupervised.final_fit() source code but I'm not sure it's true.
**load_best_model()** seems to return the original best model in searching phase.

Thank you.

**Comment by jhfjhfj1** [comment]
This might be a bug. I will investigate it. @twprinston Thanks.

**Comment by kavehtp** [comment]
Faced a similar problem:

After training the model using `clf.fit()` function, calling `clf.final_fit()` does not make any difference. The best model remains the same and does not get updated. So:
```
clf = ak.ImageClassifier(verbose=True, resume=True, path='autokeras-run')	
clf.final_fit(x_train, y_train, x_dev, y_dev, retrain=True)
y_test_pred = clf.predict(x_test)
```
leads to exactly the same results as:
```
clf = ak.ImageClassifier(verbose=True, resume=True, path='autokeras-run')
y_test_pred = clf.predict(x_test)
```
