### ISSUE TITLE
Link to autokeras.com

### ISSUE THREAD

**Issue by impredicative** [jhfjhfj1/autokeras#25]
Please add a link to the docs at http://autokeras.com/ in the readme of this repo. Thanks.

**Comment by jhfjhfj1** [comment]
Thank you.
Just added.

**Comment by impredicative** [comment]
You did? I don't see it.

**Comment by jhfjhfj1** [comment]
Add a documentation badge in README.md.
https://docs.readthedocs.io/en/latest/badges.html
