### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by bersbersbers** [jhfjhfj1/autokeras#256]
I have read through the documentation, and a few things are not clear to me that I feel should be:

1. Is autokeras only for classification tasks?
2. Which backend does autokeras use? It depends on tensorflow and torch - which ones does it actually use?
3. Can you use an existing keras model as a starting point for optimization?

**Comment by jhfjhfj1** [comment]
@bersbersbers We will improve the documentations right after we finished some of our features. Thank you for your suggestion.

1. It can do regression.
2. It use pytorch. tensorflow and keras are for exporting keras model.
3. Currently we do not support it.

**Comment by bersbersbers** [comment]
Thanks, very helpful!
