### ISSUE TITLE
How to define a search space?

### ISSUE THREAD

**Issue by moon412** [jhfjhfj1/autokeras#259]
Hi,

AutoKeras is very cool! Thanks for the impressive work. I've read the tutorials on the website. The API is very straightforward.

One thing I am missing is how to define a customized search space. When I look at the source code, I realize it is in the search.py file. So I don't think I can directly use ImageClassifier to customize the search space with some constraints. Is it correct? Is there a way to do that with AutoKeras?

Thanks!

**Comment by jhfjhfj1** [comment]
Currently, you cannot customize it with the API. You can only customize it by forking and changing the code yourself, which is not very easy to do. Thanks.
