### ISSUE TITLE
Limit the search space by depth and with of the layers

### ISSUE THREAD

**Issue by malizheng** [jhfjhfj1/autokeras#262]
Dear @jhfjhfj1 ：
  I'm trying to apply autoKeras on cifar10 datasets (GPU:gtx 1080Ti) .
   ```
 (x_train, y_train), (x_test, y_test) = cifar10.load_data()
    clf = ImageClassifier(path='result/cifar10',verbose=True, augment=True,resume =True)
    clf.fit(x_train, y_train, time_limit=12 * 60 * 60)
```

 The result of the first trial was stuck in 60 model with "Current model size is too big. Discontinuing training this model to search for other models "（The best of Metric Value：0.84）.

 The result of the second trial was stuck in 22 model with " Current model size is too big. Discontinuing training this model to search for other models "（The best of Metric Value：0.83）.

 The result of the third trial was stuck in 20 model with "Current model size is too big. Discontinuing training this model to search for other models "（The best of Metric Value：0.82）.

After trying it a few times，Search stuck in one model and was always in this problem in each trial.

It is difficult for me to achieve the accuracy provided in the paper.
What should I set up on autokeras to achieve Metric Value 0.8856 in the paper? 
Or can you provide the best model produced by the program？
Or can you provide an example  on  cifar10?

Thank you very much！

**Comment by jhfjhfj1** [comment]
@malizheng Thank you! This is an important issue we need to solve.
