### ISSUE TITLE
model predict issues

### ISSUE THREAD

**Issue by xuean009** [jhfjhfj1/autokeras#274]
load model predict result is [-0.32936123 -0.3601544   1.7912102   0.03495846 -0.6662229 ]
how to transform labels?
thank you

**Comment by jhfjhfj1** [comment]
@xuean009  Would you please provide the code for how you saved the model? Thanks.

**Comment by xuean009** [comment]
@jhfjhfj1 
model.load_searcher().load_best_model().produce_keras_model().save(MODEL_DIR)
