### ISSUE TITLE
load_image_dataset does not support different image size

### ISSUE THREAD

**Issue by parap1uie-s** [jhfjhfj1/autokeras#275]
### Bug Description

`load_image_dataset` does not support different image size

```
File "//site-packages/autokeras/image_supervised.py", line 85, in read_images
    return np.asanyarray(x_train)
  File "//site-packages/site-packages/numpy/core/numeric.py", line 553, in asanyarray
    return array(a, dtype, copy=False, order=order, subok=True)
ValueError: could not broadcast input array from shape (256,256,3) into shape (256)
```

### Reproducing Steps
  * Step 1: Get some images with different shape. For example: 100x(256,256,3) and 1x(256,255,3)
  * Step 2: Use `load_image_dataset` to load images.

### Expected Behavior

A automatic parameter to get the size that most of images has, and reshape any images with different shape.

Or a external parameter, modify
`read_images(img_file_names, images_dir_path)`  @ line 64, image_supervised.py

to 

`read_images(img_file_names, images_dir_path, images_size)`

**Comment by jhfjhfj1** [comment]
This is fixed in the latest version. Thanks.
