### ISSUE TITLE
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Eton** [jhfjhfj1/autokeras#279]
Hi, everybody, sorry for my poor English.

I got a problem.

OS : Linux Centos 7
CUDA 9.0.176_384.81
CUDNN 7.3.0 or 7.2.1 or 7.0.5  
TensorFlow 1.10.0
AutoKeras 0.2.18
Keras 2.2.2

Training model by Tensorflow was fine. 
Load model by keras was fine.

But when I use ImageClassifier from autokeras.image_supervised 

I got ImportError libcublas.so.9.0: cannot open shared object file: No such file or directory.

I already set CUDA_HOME (/usr/loacl/cuda) and LD_LIBRARY_PATH (/usr/local/cuda/lib64) in bashrc.

could somebody meet same issue?

could somebody share your software version?

thanks.

**Comment by mlaradji** [comment]
Hi Eton,

Could you post a sample of the code with `ImageClassifier` that failed for you? I would like to test it on my system.

**Comment by Eton** [comment]
Hi Mlaradji,

Here is my samlpe of code

```
from autokeras.image_supervised import ImageClassifier

if __name__ == '__main__':

   # get image data from factory......
  
   x_train = # get training data 
   y_train = # get label of training data
   x_test = # get test data 
   y_test = # get label of test data

    x_train = x_train.reshape(x_train.shape + (1,))
    x_test = x_test.reshape(x_test.shape + (1,))

    clf = ImageClassifier(verbose=True)
    clf.fit(x_train, y_train, time_limit=12 * 60 * 60)
    clf.final_fit(x_train, y_train, x_test, y_test, retrain=True)
    y = clf.evaluate(x_test, y_test)
    print(y)
```

Sample code just like example of autokeras official website.

Thank you.

**Comment by Eton** [comment]
thanks @mlaradji  

I will try to manually compile TensorFlow.
