### ISSUE TITLE
Docker image request

### ISSUE THREAD

**Issue by alessando-guida** [jhfjhfj1/autokeras#280]
### Feature Description

Create a public docker image container with the environment required to run autokeras without having to worry about dependency conflicts. 

### Reason

Having difficulties recreating the environment to run autokeras without running in dependencies issues.

**Comment by maximilianley** [comment]
Hi, just wanted to say thanks for creating the environment. Had the same problem with dependencies when trying to install autokeras. Makes it a lot easier. 
I was just trying to run the pre-trained model object_detector.py . But it seems like the autokeras version in the image is version 0.3.1 and doesn't have some features that the newest version has, such as pre-trained models. Just wanted to ask if there's a way to include object_detector in the current docker image? Thanks
