### ISSUE TITLE
ImportError: cannot import name 'ImageRegressor'

### ISSUE THREAD

**Issue by wangpupanjing** [jhfjhfj1/autokeras#298]
from autokeras import ImageRegressor

[root@hz21-gpu-1804-p025 autokeras]# python autokeras_idcard_point.py 
/lianlian/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Traceback (most recent call last):
  File "autokeras_idcard_point.py", line 19, in <module>
    from autokeras import ImageRegressor
ImportError: cannot import name 'ImageRegressor'

**Comment by jhfjhfj1** [comment]
This issue is fixed in the latest version. Thanks.
