### ISSUE TITLE
Error in code_reuse_example.py

### ISSUE THREAD

**Issue by CBrauer** [jhfjhfj1/autokeras#299]
I'm trying to execute the example:  "code_reuse_example.py".
I get the following error:

![auto-keras](https://user-images.githubusercontent.com/1317234/48090836-cf21cc00-e1bc-11e8-8c93-8d3fb1820d11.png)

**Comment by jhfjhfj1** [comment]
We are getting rid of GPUtil now. It should work find now. Thanks.
