### ISSUE TITLE
tqdm doesn't work on google colab

### ISSUE THREAD

**Issue by tl-yang** [jhfjhfj1/autokeras#307]
### Bug Description
As mentioned by @shyamalschandra.

According to [tqdm issue#558](https://github.com/tqdm/tqdm/issues/558)
tqdm.notebook can't work on Google Colab due to the lack of **ipywidgets**

### Reproducing Steps
  * Step 1: pip3 install autokeras on google colab
  * Step 2: run example/mnist.py by coping and pasting the code in Google Colab.

### Expected Behavior
Should be working without error

### Setup Details
Include the details about the versions of:
 - OS type and version: Google Colab
 - Python: 3.6
 - autokeras: 0.2.18
 - scikit-learn: 0.19.1
 - numpy: 1.14.5
 - keras: 2.2.2
 - scipy:
 - tensorflow: 1.10.0
 - pytorch: 0.4.1
 - tqdm: 4.25.0

### Additional context
Could be solved by replacing 
```python
from tqdm.autonotebook import tqdm
```
to
```python
from tqdm import tqdm
```
***However, the final progress bar will remain on the terminal***

**Comment by chengs** [comment]
Hi, I am a tqdm developer and am trying to address this problem.
I have a PR which has minimal function https://github.com/tqdm/tqdm/pull/640
Could you please try it and give me some feedbacks? (eg. If it is enough for you).

**Comment by tl-yang** [comment]
Hi @chengs, thanks for the great work. With the patch, tqdm should be able to support tqdm.notebook on Google Colab, Is my understanding correct?  
I've tried our original usage of tqdm:
```python
from tqdm.autonotebook import tqdm
progress_bar = tqdm(total=len(
    desc='Epoch-'
    + str(self.current_epoch)
    + ', Current Metric - '
    + str(self.current_metric_value),
    file=sys.stdout,
    leave=False,
    ncols=100,
    position=0,
    unit=' batch')
``` 
Still I got the same error code.

**Comment by chengs** [comment]
@tl-yang Yes, although it is hard to implement ALL the tqdm features since there is no ipywidgets support, my plan is to implement a ugly but workable progressbar without the support of ipywidgets.

I will check your case and try to make it work.

**Comment by tl-yang** [comment]
@chengs Do you have any update on this?

**Comment by chengs** [comment]
I implement the basic function. Please see the demo here. https://colab.research.google.com/drive/12QXaI5ZAiQJfK-19HVl8fyjyh79B-TMf

**Comment by nyck33** [comment]
Is it usable on Colab now?  It seems to mess with it still.

**Comment by ktanay20** [comment]
@nyck33 For me it is still a mess
