### ISSUE TITLE
I wonder what is the max or min image size in autokeras?

### ISSUE THREAD

**Issue by zhangjinyangnwpu** [jhfjhfj1/autokeras#310]
I want to deal a hyperspectral image data, and it's shape with (1800,) (1800, 103) for train data and train label, when I use the autokeras.image_supervised.ImageClassifier() method, I find that the input size must a 4 dimension format, so I reshape the train data with shape (1800, 103, 1, 1), and I got this error:
```
Traceback (most recent call last):
  File "E:/自主进化/Code/AutoKeras/HSI.py", line 50, in <module>
    clf.fit(train_data, train_label, time_limit=12 * 60 * 60)
  File "C:\Users\lab103\Anaconda3\lib\site-packages\autokeras\image_supervised.py", line 239, in fit
    run_searcher_once(train_data, test_data, self.path, int(time_remain))
  File "C:\Users\lab103\Anaconda3\lib\site-packages\autokeras\image_supervised.py", line 40, in run_searcher_once
    searcher.search(train_data, test_data, timeout)
  File "C:\Users\lab103\Anaconda3\lib\site-packages\autokeras\search.py", line 222, in search
    raise e
  File "C:\Users\lab103\Anaconda3\lib\site-packages\autokeras\search.py", line 204, in search
    metric_value, loss, graph = train_results.get(timeout=remaining_time)[0]
  File "C:\Users\lab103\Anaconda3\lib\multiprocessing\pool.py", line 644, in get
    raise self._value
RuntimeError: Given input size: (64x103x1). Calculated output size: (64x51x0). Output size is too small at c:\programdata\miniconda3\conda-bld\pytorch_1533090623466\work\aten\src\thnn\generic/SpatialDilatedMaxPooling.c:67

Process finished with exit code 1
```
maybe it caused because the third dimension is too small, so I wonder what's the image size boundary for autokeras when I use it?

**Comment by 2fasc** [comment]
If you use PyTorch the input to a ConvNet should be shaped like [batch, channels, height, width].

Keras offers two modes: "channels_last" corresponds to inputs with shape (batch, height, width, channels) while "channels_first" corresponds to inputs with shape (batch, channels, height, width)" https://keras.io/layers/convolutional/

My take on what sets the max size of an image is that your batch of images should fit into your RAM.

**Comment by zhangjinyangnwpu** [comment]
which I mean is that if I use a pic with shape 28*28, autokeras may normal, but when I take a pic with shape 28*1, it out put the output size is too small, so I wander what is the max or min pic shape for autokeras, thank you.

**Comment by jhfjhfj1** [comment]
We will be supporting any size image in the future.
Currently, we don't have an upper limit.
Only a lower limit which is image still larger than 1 after three pooling layers with stride 2.

**Comment by songqiqqq** [comment]
> We will be supporting any size image in the future.
> Currently, we don't have an upper limit.
> Only a lower limit which is image still larger than 1 after three pooling layers with stride 2.

the statement "larger than 1 after three pooling layers with stride 2" means the low limit of image dimension is 16 ?  Is there a exact number for this question ? or the low limit could be changed somewhere in the source code ? @jhfjhfj1
