### ISSUE TITLE
Why contain GAN in this project ?

### ISSUE THREAD

**Issue by svjack** [jhfjhfj1/autokeras#314]
I have seen gan part (implement by DCGAN) in image, but it seems like, this part not
 use auto adjust function provide as CnnModule (used in image_supervised.py or text_surpervised.py)
I can understand that the construction of GAN is closed to fixed rather than can change by
 auto adjust.
But, is there any example, or idea that can change GAN's construction by use Auto-Keras ?
Or it will be add in the feature.

And are there any complicated task such as image segemtatiion 、detection or other nlp tasks than solely apply classification or regression use Auto-Keras,
I mainly focus on the change methods on search appropriated neural networks's construction.

Look forward to your favourable reply.

**Comment by jhfjhfj1** [comment]
It will be added in the future.
GAN is very hard to train for non-experts.
We are trying to automate it as much as possible.
Finally, it would only require the data to train a GAN.
Thanks.
