### ISSUE TITLE
Implement small batch size for Image Classifier

### ISSUE THREAD

**Issue by dk33145** [jhfjhfj1/autokeras#334]
### Feature Description
Implement small batch loading into clf.  (ie, batch_size  = 32, 64 etc)

### Reason
Image Classifier currently loads all train and test data into memory at once. This is very inefficient and taxing for the system.

### Solution
Add small batch loading to Imageclassifier

**Comment by JasonKitty** [comment]
I agree with you.

**Comment by jhfjhfj1** [comment]
If you want to use this feature, you need to preprocess your data and call the CnnModule instead of ImageClassifier. During you pack your pytorch datasets, you need to implement the batch loading. Thanks.
