### ISSUE TITLE
ModuleNotFoundError: No module named 'autokeras.image_supervised'

### ISSUE THREAD

**Issue by wanghao8401** [jhfjhfj1/autokeras#336]
"import autokeras as ak" has no problem, but when I run "from autokeras.image_supervised import ImageClassifier", it gives the error messages:  No module named 'autokeras.image_supervised'.

Any helps is appreciated!

**Comment by aojue1109** [comment]
Direct operation：
import autokeras as ak
clf = ak.ImageClassifier(verbose=True)

**Comment by wanghao8401** [comment]
Thank you so much!
