### ISSUE TITLE
 Batch training function request

### ISSUE THREAD

**Issue by aojue1109** [jhfjhfj1/autokeras#338]
Batch training can be added during the training process

### Feature Description

I am performing a picture classification training task. The server memory size is 16GB, and the size of 100 pictures is 299*299*3. There is a memory overflow problem during the training process. Compared to the kears image, there are no memory problems in the same size.

### Reason

PyTorch has a flaw in the use of memory, a small amount of picture training will take up a lot of memory

### Solution

It is recommended to optimize memory usage, giving the size, number of training images and detailed parameters of the server configuration. At the same time increase the function of batch training and support picture size selection

**Comment by svjack** [comment]
It use pytorch DataSet api to load data, you may try implement a pytorch Dataset to fix it.

**Comment by jhfjhfj1** [comment]
You can implement your own pytorch Dataset and call the CnnModule.
