### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'

### ISSUE THREAD

**Issue by Npccc** [jhfjhfj1/autokeras#348]
### Bug Description
i use ImageClassifier method but i get this exception when training model , are you tell me why ? and how to fix this issue ?. Thanks

+----------------------------------------------+
|               Training model 3               |
+----------------------------------------------+
Using TensorFlow backend.
                                                                                                    
No loss decrease after 5 epochs.

+--------------------------------------------------------------------------+
|    Father Model ID     |                 Added Operation                 |
+--------------------------------------------------------------------------+
|                        |             to_deeper_model 34 ReLU             |
|           1            |               to_wider_model 7 64               |
+--------------------------------------------------------------------------+

Saving model.
+--------------------------------------------------------------------------+
|        Model ID        |          Loss          |      Metric Value      |
+--------------------------------------------------------------------------+
|           3            |   5.837443938292563    |         0.512          |
+--------------------------------------------------------------------------+
Exception ignored in: <bound method StorageRef.__del__ of <torch.multiprocessing.reductions.StorageRef object at 0x7ff87585d4a8>>
Traceback (most recent call last):
  File "/home/guost/anaconda3/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 26, in __del__
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <bound method StorageRef.__del__ of <torch.multiprocessing.reductions.StorageRef object at 0x7ff87585d5c0>>
Traceback (most recent call last):
  File "/home/guost/anaconda3/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 26, in __del__
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <bound method StorageRef.__del__ of <torch.multiprocessing.reductions.StorageRef object at 0x7ff87585d6d8>>
Traceback (most recent call last):
  File "/home/guost/anaconda3/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 26, in __del__
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'
Exception ignored in: <bound method StorageRef.__del__ of <torch.multiprocessing.reductions.StorageRef object at 0x7ff87584cba8>>
Traceback (most recent call last):
  File "/home/guost/anaconda3/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 26, in __del__
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'

**Comment by tl-yang** [comment]
I think this is related o #311 . @Npccc  Can you provide more detail? what is the version you're using. Are you running mnist example or ?

**Comment by jhfjhfj1** [comment]
@Npccc We have just fixed a bug that might cause this problem. You can try with the latest version 0.3.4. Thanks.

**Comment by Npccc** [comment]
@tl-yang 
**My enviroment：**
autokeras：'0.3.3'
python：3.6.6
torch:0.4.1
keras:2.2.4
tensorflow:1.12.0
system:Ubuntu16.04
numpy:1.15.2

**My code:**
I'm running on my own dataset

`from autokeras.image.image_supervised import load_image_dataset, ImageClassifier
from keras.models import load_model
from keras.utils import plot_model
from keras.preprocessing.image import load_img, img_to_array
import numpy as np
import torch
TRAIN_CSV_DIR = '/home/guost/Datasets/Dog/C5/NewAg128/train_labels.csv'
TRAIN_IMG_DIR = '/home/guost/Datasets/Dog/C5/NewAg128/train'
TEST_CSV_DIR = '/home/guost/Datasets/Dog/C5/NewAg128/test_labels.csv'
TEST_IMG_DIR = '/home/guost/Datasets/Dog/C5/NewAg128/test'

if __name__ == '__main__':
    train_data, train_labels = load_image_dataset(csv_file_path=TRAIN_CSV_DIR, images_path=TRAIN_IMG_DIR)
    test_data, test_labels = load_image_dataset(csv_file_path=TEST_CSV_DIR, images_path=TEST_IMG_DIR)
    train_data = train_data.astype('float32') / 255.
    test_data = test_data.astype('float32') / 255.
    clf = ImageClassifier(verbose=True,path='/home/guost/autokeras/Newversion/1128/modelPath',resume=False)
    clf.fit(train_data, train_labels,x_test=test_data,y_test=test_labels, time_limit=30 * 60)
    clf.final_fit(train_data, train_labels, test_data, test_labels, retrain=True)
    y = clf.evaluate(test_data, test_labels)
    print("evaluate:", y)`

Thank  @tl-yang

**Comment by Npccc** [comment]
I'll try,Thank you. @jhfjhfj1
