### ISSUE TITLE
TextClassifier

### ISSUE THREAD

**Issue by secsilm** [jhfjhfj1/autokeras#35]
I see `ImageClassifier` in the doc. Is there something like `TextClassifier` to process text?

**Comment by davidlenz** [comment]
+1 would also be interested in auto text classifier

**Comment by HalaKuwatly** [comment]
same here!

**Comment by jhfjhfj1** [comment]
Thank you for the suggestion.
We are working on this feature now.
It would be online soon.

Thanks.

**Comment by jhfjhfj1** [comment]
### Suggested Name

TextClassifier
### Task Description

Text classifiation
### Evaluation Metrics

Accuracy

### Benchmark Datasets

Penn Treebank
### Reason

NA
### Solution

NA
### Additional Context

NA

**Comment by jhfjhfj1** [comment]
@boyuangong Please write a baseline for the TextClassifier.
It needs to extend from the supervised.py.
And reuse the class of ModelTrainer in utils.py.
Currently, it doesn't need to search for multiple architectures.
Just use a default architecture for now.

We can have a meeting to discuss if you have questions.
Thanks.

**Comment by ddofer** [comment]
Re: TextClassifier benchmarks:
I would suggest starting with a document/sentence leve lclassification model (not word level/many to many). e.g. IMDB sentiment. (Common benchmark for sentiment classification of short documents. Used to benchmark ULMFit amongst others).
https://github.com/keras-team/keras/blob/master/keras/datasets/imdb.py
http://nlp.fast.ai/classification/2018/05/15/introducting-ulmfit.html

**Comment by jhfjhfj1** [comment]
@ddofer Thank you for your suggestions.

**Comment by ziyadi** [comment]
When do you expect to release the initial TextClassifier model?

**Comment by mohammadKhalifa** [comment]
@boyuangong  I can help you out with that module if that's okay.

**Comment by boyuangong** [comment]
Hi there,   
  

  
Thanks a lot. I will send the pull request of the newst version tonight when I come back home. The model is pretty much complete now. Only   have some run out of memory problem. It would be great to receive help from you.   
  
  
  
  
 -- Best Boyuan Gong  
      
  

  
  
>

**Comment by DGaffney** [comment]
@boyuangong is this live yet? Is there a branch where the code lives currently? Very excited to see your work!

**Comment by DGaffney** [comment]
Woooooo!

**Comment by renaudham** [comment]
Hi.
Great, what is the status?

Some questions
-What is the max length of each texts we want to classify? For example can, we proceed an average email ?
-How many classes can we feed in the engine, so it could stay relatively average with not too much false positive ? 20, 50?
I know many old classifier drop a lot in accuracy if there is too many classes.
But recent one like the openSource from Facebook can stand really more. But I don't want to use anything from facebook.

-What is the format to feed for training and then testing ? I didn't see any docs and tutorials yet, is there?

Thanks, great job.

**Comment by boyuangong** [comment]
@renaudham Hi, thanks for your interesting in our work. We are preparing the tutorial documents for some modules including the textClassifier. You can directly check this in the new [pull request 341](https://github.com/jhfjhfj1/autokeras/pull/341/files). The text tutorial are in text.md. 

Also, if you want to try the textClassifier. You can go and check the example in examples/text_cnn.  

Please feel free to let me know if you have further questions.
