### ISSUE TITLE
Use of tensorflow-GPU

### ISSUE THREAD

**Issue by paulhacosta** [jhfjhfj1/autokeras#358]
Do you have any recommendations on the use of tensorflow-gpu?

### Description

I am currently attempting to run AutoKeras in my institution's HPC, but it is highly encouraged to use tensorflor-gpu in order to correctly use the gpu. As you know, autokeras does not include tensorflow-gpu. Will having two versions of tensorflow have any effect on autokeras? Will it create a conflict?

### Current tensorflow
tensorflow=1.10.0
  
### Alternative Solutions
Install the matching version of tensorflow-gpu

pip install tensorflow-gpu=1.10.0

**Comment by hemangjoshi37a** [comment]
Upgrade autokeras, now it supporta GPU.

**Comment by alperyilmaz** [comment]
what is the autokeras version that supports tensorflow-gpu? is it 0.3.5?

**Comment by jhfjhfj1** [comment]
@alperyilmaz We mainly use pytorch.
