### ISSUE TITLE
Running Experiment with AutoKeras

### ISSUE THREAD

**Issue by paulhacosta** [jhfjhfj1/autokeras#359]
### Description
Hi,

I have been successful in running the MNIST training example that you provided in the repository. Thank you for the demonstration. I have also read the AUTO-KERAS: EFFICIENT NEURAL ARCHITECTURE SEARCH WITH NETWORK MORPHISM paper. Now, I would like to apply AutoKeras to my own data set, a relatively small data set, but I need to know a couple of things.

### Questions
1. Is it possible to set a random seed to make the classification experiments reproducible? If so, where can I set the seed?
2. I will be running my experiment on a cluster node with 2 gpu cards. Is it possible to use two cards at once, and train two models at once to maximize efficiency? 
3. How is the first model constructed, and how are subsequent models constructed from the results of previously constructed models? 

### Additional Info 
For question 3, I understand the workflow described in your paper, but I am looking for a more technical explanation or guide. 

Thank you!

**Comment by isaac-gs** [comment]
1. Your experiments should be robust to random variable change. I would recommend running several times and averaging the results to get a "realistic" estimation of performance.
2. This does not seem to be supported (see link). You could run each of several iterations of this experiment on each of your GPUs.

https://github.com/jhfjhfj1/autokeras/issues/60
