### ISSUE TITLE
PortableImageSupervised.predict is slow with many images

### ISSUE THREAD

**Issue by sammy-yusuke** [jhfjhfj1/autokeras#360]
# Bug Description (maybe feature enhancement.)
PortableImageSupervised.predict method on the cifar10 test dataset is a bit slower when test dataset size is bigger. The number of images in the dataset is 10000.
Maybe predict should be run on gpu like the code in the url above?
https://github.com/jhfjhfj1/autokeras/compare/master...sammy-yusuke:0e71db8dab4841a577c7943daf4bfdb19acbfc0c

### Reproducing Steps
1. Place all files in the URL below into some dir
https://gist.github.com/sammy-yusuke/bc8aa440d2fdbe3908198fdcf82442e2
2. Train model
```
python train_cifar10.py --timelimit-h 0.5 --dataset cifar10
```
3. Test model
```
python test_cifar10.py --training-output-path ~/nas_try/${trained_date}
```
### Expected Behavior
Step 3 should finish in at least 30 min.

### Setup Details
Include the details about the versions of:
 - OS type and version: Description:    Ubuntu 16.04.5 LTS
 - Python: 3.6.6
 - autokeras: master
 - scikit-learn:0.19.1
 - numpy:1.14.5
 - keras:2.2.2
 - scipy:1.1.0
 - tensorflow:1.10.0
 - pytorch:0.4.1

### Additional context
I was just trying to see all the results of all searched models by autokeras.

**Comment by jhfjhfj1** [comment]
@satyakesav Would you please fix this issue?

I think it can be solved by moving this line https://github.com/jhfjhfj1/autokeras/blob/master/autokeras/image/image_supervised.py#L279
to the predict() function.
