### ISSUE TITLE
Export Keras model after fit

### ISSUE THREAD

**Issue by jetjodh** [jhfjhfj1/autokeras#37]
I want to save the trained model and make it usable for serving. Is it possible? How?

**Comment by paindefender** [comment]
I believe you can get the model using `clf.load_searcher().load_best_model()`

**Comment by paindefender** [comment]
I think you can get the model using `clf.load_searcher().load_best_model()`

**Comment by jhfjhfj1** [comment]
Thank @paindefender for the help.

@ankapale 
Please add a function of export keras_model() to the ImageClassifier
by clf.load_searcher().load_best_model().produce_keras_model() here.
https://github.com/jhfjhfj1/autokeras/blob/master/autokeras/graph.py#L542

Thanks.

We also need to find a way to export our own model instead of the Keras model.
I will open an issue on that.

**Comment by adriantorrie** [comment]
Can you look to export using onnx standard? 

So models are interoperable and deployable to production environments.

[https://onnx.ai](https://onnx.ai)

**Comment by rckoepke** [comment]
#Replicating the save-file code from commit a3ca627 :

from autokeras import ImageClassifier
clf = ImageClassifier(verbose=True, augment=False)
clf.load_searcher().load_best_model().produce_keras_model().save('test_save.h5')

#This appears successful. Returns null, but a new 7.3MB file 'test_save.h5' is generated from /tmp/autokeras/12.h5 which was originally 7.0MB.

#Using Keras to plot the newly-saved model:

from keras.models import load_model
model = load_model('test_save.h5')
from keras.utils import plot_model
plot_model(model, to_file='model.png')
#The result of this is successful, the architecture is plotted to an image.


#Can also output just the architecture:
from autokeras import ImageClassifier
clf = ImageClassifier(verbose=True, augment=False)
clf.load_searcher().load_best_model().produce_keras_model().to_json()
