### ISSUE TITLE
How to load local pre-trained vectors?

### ISSUE THREAD

**Issue by luckystar1992** [jhfjhfj1/autokeras#386]
In the TextClassifier class,  autokeras download pre-trained vectors (Glove) from the internet. But I want to load my pre-trained word embedding in local disk, So how can I code it?

**Comment by luckystar1992** [comment]
I have replaced the glove vector file in the /tem/autokeras_store/glove floder, and it works fine.

**Comment by YASIRAQ** [comment]
hello . I have text classification issue . I want to keep everything as auto except I want to specify word2vec 
technique as word embedding . how can I do that ? thank you
