### ISSUE TITLE
Cuda device successfully detected. However, nvidia-smi cannot be invoked

### ISSUE THREAD

**Issue by kctoayo88** [jhfjhfj1/autokeras#391]
Hello,
My environment is 

Python 3.6
Windows 10
Autokeras 0.3.5
Pytorch 0.4.1
tensorflow 1.10.0

When I try to run the ImageClassifier
and it will show me 
Cuda device successfully detected. However, nvidia-smi cannot be invoked, but keep running

I 'm try to use gpu to process, but it only using cpu and very slow
Somebody can help me?

**Comment by JasonKitty** [comment]
I met the same problem as you.
My solution is to add this path C:\Program Files\NVIDIA Corporation\NVSMI to System environment variable.

**Comment by tl-yang** [comment]
@JasonKitty @kctoayo88  Exactly, you'll have to let nvidia-smi command work to use gpu on AutoKeras because we'll use the command to determine which gpu to use. In the future, we may add a custom parameter to let user specify the device id.

**Comment by JannesRausch** [comment]
Hey i have the same Problem. @JasonKitty  how should I call the enviroment variable
