### ISSUE TITLE
Delete the GPUtil dependency

### ISSUE THREAD

**Issue by jhfjhfj1** [jhfjhfj1/autokeras#399]
### Feature Description

Delete the GPUtil package dependency in Auto Keras.

### Reason

Let users to decide which GPU to use.

### Solution

Delete the GPUtil usage in the text classification and regression part.

**Comment by hemangjoshi37a** [comment]
Or may be we can prompt user at the time of installation of autokeras which GPU they have.

**Comment by jhfjhfj1** [comment]
This issue is solved by removing the GPUtil.
The user can specify the GPU by setting the environmental variable.
