### ISSUE TITLE
Possible to use for 3D convolutioanl neural network?

### ISSUE THREAD

**Issue by xuzhang5788** [jhfjhfj1/autokeras#40]
You only support the image classification problems. Am I right? If my problem is similar to the image classification, but my input images are 3D instead of 2D. Can I still use your AutoKeras to figure out the better architectures and hyperparameters for 3D convolutional neural networks? Thanks for sharing your library.

**Comment by jhfjhfj1** [comment]
Thank you for your interest in our project.

Currently, we do not support this feature, but you can submit an issue of "feature request" if you really in need.

**Comment by srijandas07** [comment]
any progress on this issue?
Thanks

**Comment by haifeng-jin** [comment]
Currently, we only support this in ConvBlock. So you may need to follow this guide to connect your own space. https://autokeras.com/tutorial/customized/
