### ISSUE TITLE
GPU and multi-GPU usage tutorial

### ISSUE THREAD

**Issue by LiLong1105** [jhfjhfj1/autokeras#440]
1, can it support multi-GPU? 

2, can it specify a certain GPU to work?
usually we can  specify a certain GPU by these codes:
`import os
os.environ["CUDA_VISIBLE_DEVICES"] = "4"`
OR
`CUDA_VISIBLE_DEVICES="4"`

Thx!

**Comment by francotheengineer** [comment]
Q2: 
In my experience, `CUDA_VISIBLE_DEVICES="0"` is the best way to prevent your terminal from seeing the other GPUs. 
This code also has some functionality to do the same within python:
```
os.environ["CUDA_DEVICE_ORDER"]="PCI_BUS_ID"   # see issue #152
os.environ["CUDA_VISIBLE_DEVICES"]=str(<gpu number>)
```
You could parse <gpu number> from arg parse or alike.

**Comment by jhfjhfj1** [comment]
@tl-yang I think we also need a tutorial just for selecting single and multiple GPUs in additional to the colab tutorial.

**Comment by bestpredicts** [comment]
does autokeras  support multi-GPU?

**Comment by haifeng-jin** [comment]
It is based on TensorFlow. So it does in a way that trains one model on multiple GPUs as distributed training.

**Comment by bestpredicts** [comment]
> It is based on TensorFlow. So it does in a way that trains one model on multiple GPUs as distributed training.


In fact, I specified two GPUs in cuda_visible_devices in the code, but when I use the fit method, he has two GPUs, but only one GPU is working.

**Comment by haifeng-jin** [comment]
I believe you can use any way that supported by tensorflow or tf.keras. AutoKeras is not doing anything to configure the GPUs to use. We just directly call the APIs of TensorFlow.
The only thing we did is to do a clear_session() before every run. Not sure if that would wipe out your gpu configuration.

**Comment by haifeng-jin** [comment]
@bestpredicts Would you help us answer another question?
In this issue, it shows you have unassigned tl-yang from the issue. You can see the log right above.
However, I don't think you have permission to do it.

Would you please let me know how did you unassigned him?
GitHub is trying to fix this bug.

**Comment by bestpredicts** [comment]
> @bestpredicts Would you help us answer another question?
> In this issue, it shows you have unassigned tl-yang from the issue. You can see the log right above.
> However, I don't think you have permission to do it.
> 
> Would you please let me know how did you unassigned him?
> GitHub is trying to fix this bug.

 Thank you for your answer, in fact I did not do any unassigned operation, I don't know why this bug was triggered  :O
