### ISSUE TITLE
speech recognition

### ISSUE THREAD

**Issue by jhfjhfj1** [jhfjhfj1/autokeras#448]
### Suggested Name

SpeechRecognizer

### Task Description

The input should be a path to an audio file.
The output should be a string of the recognized text from the speech audio.
It is a pretrained model and can only recognize English.
See if it can reuse the code of voice generator.

**Comment by wjnodejs** [comment]
There is a murmur by voice_generation for text to voice

**Comment by S-Dutta1** [comment]
Could you please point to any tutorial / example for using this feature

**Comment by haifeng-jin** [comment]
We have removed this feature since the performance is not good enough and it is just a pretrained model which doesn't support training.
