### ISSUE TITLE
Refactor the google drive downloader to the utils for general use

### ISSUE THREAD

**Issue by boyuangong** [jhfjhfj1/autokeras#455]
### Reason
Currently it's in the voice generator.

### Solution
Refactor the  autokeras/autokeras/pretrained/voice_generator/google_drive_download.py file.

**Comment by jhfjhfj1** [comment]
Another pull request is needed for changing all the download into this format, including all the pretrained models. You may "find usage" of the original download function to see where to make the changes. Thanks. @boyuangong

**Comment by jhfjhfj1** [comment]
@boyuangong Since we have created the team drive. Please move all the models there. Thanks.
