### ISSUE TITLE
Website SSL certification is wrong

### ISSUE THREAD

**Issue by itemx** [jhfjhfj1/autokeras#48]
Cool project!

But while I tried to accesso https://autokeras.com/ I'll receive an SSL error from browser, the certification is issued for github only.

You may change the configuration from website's repo at:

![1533468353055](https://user-images.githubusercontent.com/18457683/43685420-7f1d38ea-98e5-11e8-9c46-fe02f75c238b.jpg)

and fill autokeras.com into that field.

**Comment by jhfjhfj1** [comment]
Thank you so much!
I just fixed the problem.
