### ISSUE TITLE
cannot import name Constant

### ISSUE THREAD

**Issue by hiteshn97** [jhfjhfj1/autokeras#49]
This is my error:

Using TensorFlow backend.
Traceback (most recent call last):
  File "autok1.py", line 3, in <module>
    from autokeras.constant import Constant
ImportError: cannot import name 'Constant'

This looks like an internal error?

**Comment by hiteshn97** [comment]
In Cifar10.py , 

Traceback (most recent call last):
  File "autok2.py", line 7, in <module>
    clf = ImageClassifier(verbose=True, augment=True)
TypeError: __init__() got an unexpected keyword argument 'augment'

this is the error, tried in both python3 and python2

**Comment by jhfjhfj1** [comment]
This issue has been fixed in the new release.
The parameter of the __init__() function has changed.

Thank you for your contribution.
