### ISSUE TITLE
can autokeras support distributed mode?

### ISSUE THREAD

**Issue by minsuk-heo** [jhfjhfj1/autokeras#50]
Thanks for Auto Keras.
I have one question.
Since searching model takes long time, I believe it would be awesome if the Autokeras supports trainining multiple models on distributed machines (parallel training). In this sense, searching time can be saved a lot.
I wonder if Auto Keras is already ready for it or have plan to support this?

Thanks!

**Comment by jhfjhfj1** [comment]
Thank you for your interest in our project.
Currently, we do not support distributed mode.

We might support it in the future.
If you really in need of this feature, you can submit a new issue using the feature request template.
Thanks.

**Comment by paulie3000** [comment]
would be fantastic if you decided to work with Berkley's Ray team to make a distributed version of this as being able to do Neural Architecture search at scale would be awesome!
