### ISSUE TITLE
Implement text classification using Google AI's BERT

### ISSUE THREAD

**Issue by satyakesav** [jhfjhfj1/autokeras#512]
### Feature Description

To create a text classification module based on Google's BERT.

### Reason

To provide users a module for text classification task.

### Solution

Implement a text classification module.

**Comment by yngtodd** [comment]
I am also interested in this. I am not sure how complicated it would be to implement something similar to BERT, but what about 1D convolutional nets? Something akin to Yoon Kim's CNN (https://arxiv.org/abs/1408.5882)?

**Comment by satyakesav** [comment]
Sorry for the misnomer. We are currently planning to only add a simple architecture at the end of BERT. It's not easy for us to implement NAS on BERT model with GPUs.
