### ISSUE TITLE
examples files

### ISSUE THREAD

**Issue by rajeeja** [jhfjhfj1/autokeras#563]
where are the files (test / train) for running this example:

https://github.com/jhfjhfj1/autokeras/blob/master/examples/a_simple_example/load_raw_image.py

**Comment by jhfjhfj1** [comment]
@song3134 Would you add the download link to the data in the start.md? Thanks.

**Comment by song3134** [comment]
The dataset could be downloaded through the link provided at:

https://autokeras.com/start/#what-if-your-data-are-raw-image-files-eg-jpg-png-bmp

Thanks!

**Comment by rajeeja** [comment]
Thanks.

_________________________________________
Rajeev
