### ISSUE TITLE
Include pre-trained models in docker image

### ISSUE THREAD

**Issue by maximilianley** [jhfjhfj1/autokeras#578]
Hi,
I'm currently using the autokeras docker image (pull request #284). I tried to use the pretrained models (more specifically object_detector.py), however I can't find any pretrained models in the docker image. It seems like the version of autokeras on docker is 0.3.1 and doesn't have all the features that the newest version does, such as pretrained models. 

Is it possible to include newer features in the current version of the image?
Or if not, could an image with the newest version of autokeras be made altogether?

**Comment by maximilianley** [comment]
just saw there's a new docker image for autokeras 0.3.7 created 20h ago

**Comment by garawalid** [comment]
@maximilianley 
I'm currently working on Docker image that tracks Github repository.
