### ISSUE TITLE
Parallel on Multiple GPUs

### ISSUE THREAD

**Issue by paindefender** [jhfjhfj1/autokeras#60]
I tried fitting the data on amazon p2.8xlarge instance(which has 8 GPUs), but it just fills the VRAM of one GPU and crashes with the cuda out of memory error. Is there any way of using all 8 GPUs?

**Comment by jageshmaharjan** [comment]
+1.

Only running on one GPU despite having four GPU on my server.

**Comment by ziyadi** [comment]
More general question:
Can we run autokeras models (e.g., ImageClassifier) on a cluster of distributed machines with each having multiple GPUs? 
I tried to run it in this fashion, but, was not successful. It seems like it only runs on one GPU in a single cluster node. 

Thanks a lot

**Comment by chuanmingliu** [comment]
Strongly looking forward to this feature!
