### ISSUE TITLE
clf.fit(x_train, y_train, time_limit=1) running for a long time on mnist

### ISSUE THREAD

**Issue by amrrs** [jhfjhfj1/autokeras#62]
Not sure if the argument time_limit is used here. This function is running for a very long time.

`clf.fit(x_train, y_train, time_limit=1)` 

Any possible reason?

Mac:

Python 3ish

**Comment by jageshmaharjan** [comment]
same issue +1

**Comment by amrrs** [comment]
@jagesh I got to know that I you have to define the time limit in the step before that
