### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/tmp/autokeras/searcher'

### ISSUE THREAD

**Issue by JeawyJang** [jhfjhfj1/autokeras#63]
I've encountered with this error
File "/home/me/venv/lib64/python3.6/site-packages/autokeras/classifier.py", line 258, in save_searcher
    pickle.dump(searcher, open(os.path.join(self.path, 'searcher'), 'wb'))
PermissionError: [Errno 13] Permission denied: '/tmp/autokeras/searcher'

I'm running this on linux server on virtual environment. Could you please give me the suggestion?

**Comment by PeterHuang2015** [comment]
A hint, just specifies a new approachable path when creating the classifier is ok. You can check it by referring docstring by help() method.

**Comment by jhfjhfj1** [comment]
Auto Keras may figure out a better default path.
It would be better if it is OS aware.
