### ISSUE TITLE
may you share code for your papers

### ISSUE THREAD

**Issue by Sandy4321** [jhfjhfj1/autokeras#65]
it would be great to share a code for 
Mining Mobile Internet Packets for Malware Detection

Multi-layer Anomaly Detection for Internet Traffic Based on Data Mining

thanks

**Comment by jhfjhfj1** [comment]
It is not an autokeras related issue.

**Comment by Sandy4321** [comment]
thanks for the answer, but how to write you by another way 
what is your email?
