### ISSUE TITLE
from: can't read /var/mail/keras.datasets

### ISSUE THREAD

**Issue by jageshmaharjan** [jhfjhfj1/autokeras#71]
**Describe the bug:**
Running an simple MNIST data classification. 
I was able to run for the first time. Next day, I tried to run the same program, I got this error message

```
(asr) maybe@maybe1:/data/jugs/asr/languageclf$ ./trainalutokeras.py 
from: can't read /var/mail/keras.datasets
from: can't read /var/mail/autokeras.classifier
./trainalutokeras.py: line 5: syntax error near unexpected token `,'
./trainalutokeras.py: line 5: `  (x_train, y_train),(x_test, y_test) = mnist.load_data()'
```
**Setup Details:**
Any details about your local setup that might be helpful in troubleshooting. Include the details about the versions of:
 - OS type and version: Ubuntu 16.04
 - Python: 3.6
 - scikit-learn: 0.19
 - numpy: 1.14.x
 - keras: 2.1.6
 - scipy: 1.0.1
 - tensorflow: 1.6

**Comment by jhfjhfj1** [comment]
I think this is a Keras related issue.
Since it is not calling the autokeras code yet before it crashes.

If you feel it is not, you can reopen the issue.

Thank you for your contribution.
