### ISSUE TITLE
ImportError: cannot import name 'Classifier'

### ISSUE THREAD

**Issue by soubh1k** [jhfjhfj1/autokeras#78]
### Bug Description
from autokeras.image_classifier import ImageClassifier

This gives the following error:

ImportError                               Traceback (most recent call last)
<ipython-input-6-4c3e68cce434> in <module>()
      1 from keras.datasets import mnist
----> 2 from autokeras.image_classifier import ImageClassifier

/usr/local/lib/python3.6/dist-packages/autokeras/image_classifier.py in <module>()
     18 from autokeras.search import BayesianSearcher, train
     19 from autokeras.utils import ensure_dir, has_file, pickle_from_file, pickle_to_file
---> 20 from autokeras.classifier import Classifier
     21 
     22 

ImportError: cannot import name 'Classifier'

### Reproducing Steps
Use this https://colab.research.google.com/drive/1it4U3H8t6fMhLBt_NFmB6vRRN2bVpxFv

### Expected Behavior
Separating classifier.py and image_classifier.py has created this problem.

### Setup Details
Include the details about the versions of:
 - OS type and version: Linux-4.14.33+-x86_64-with-Ubuntu-17.10-artful
 - Python: 3.6.3
 - scikit-learn: 0.19.1
 - numpy: 1.14.5
 - keras: 2.2.2
 - scipy: 0.19.1
 - tensorflow: 1.10.0
 - pytorch: 0.4.0

**Comment by jhfjhfj1** [comment]
Thank you for the bug report.
I just fixed it by changing the examples.
You can reopen the issue if it still fails.

Thanks.

**Comment by ZER-0-NE** [comment]
@jhfjhfj1 
Running on Google Colab:
```
/usr/local/lib/python3.6/dist-packages/autokeras/__init__.py in <module>()
----> 1 from autokeras.image.image_supervised import ImageClassifier, ImageRegressor, PortableImageSupervised
      2 from autokeras.text.text_supervised import TextClassifier
      3 from autokeras.net_module import CnnModule, MlpModule

ImportError: cannot import name 'ImageClassifier'
```
Code:

```
# !pip install autokeras
from autokeras.image.image_supervised import ImageClassifier
from autokeras.image.image_supervised import load_image_dataset


x_train, y_train = load_image_dataset(csv_file_path="train/label.csv",
                                      images_path="train")
print(x_train.shape)
print(y_train.shape)

x_test, y_test = load_image_dataset(csv_file_path="val/label.csv",
                                    images_path="val")
print(x_test.shape)
print(y_test.shape)
```
