### ISSUE TITLE
Export the autokeras model

### ISSUE THREAD

**Issue by jhfjhfj1** [jhfjhfj1/autokeras#79]
### Feature Description

Export the Autokeras model of its own type instead of exporting the Keras model.

### Reason

More flexible than Keras model.

### Solution

Create a base class which can only be loaded and do the "predict" and "evaluation" function.
A class named "PortableImageClassifer" extends the base class.
It has a member of an instance of "Graph".
Refer to other parts of the project to see how to do "predict" and "evaluation" with an instance of Graph.

### Alternative Solutions

NA

### Additional Context

NA

**Comment by adriantorrie** [comment]
Can you look to export using onnx standard? 

So models are interoperable and deployable to production environments.

[https://onnx.ai](https://onnx.ai)
