### ISSUE TITLE
ImageClassifier3D

### ISSUE THREAD

**Issue by xuzhang5788** [jhfjhfj1/autokeras#84]
### Feature Description
 
Your library can do 3D convolutional auto keras.

### Reason

Input images are 3D images, such as 3D CT scan images.  

### Solution

If you add this feature, it will benefit many people.
 
### Benchmark Datasets
[3D-MINST](https://www.kaggle.com/daavoo/3d-mnist/data#full_dataset_vectors.h5)

**Comment by bhack** [comment]
It could also be interesting to explore separable convolution. See https://github.com/tensorflow/hub/issues/49.

**Comment by jhfjhfj1** [comment]
@bhack Thanks! Very good suggestion.

**Comment by bhack** [comment]
And  https://arxiv.org/abs/1807.11473
